// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: proto/openpay/v1/audit.proto

/* eslint-disable */

export const protobufPackage = "v1";

/**
 * AuditEntry is one recorded change: who, what, to which resource, and the
 * state before and after.
 */
export interface AuditEntry {
  id: string;
  /** operator, service or system. */
  actorType: string;
  /** The OpenAuth user, the service credential, or "system". */
  actorId: string;
  /** Dotted past tense, e.g. wallet_type.updated. */
  action: string;
  resourceType: string;
  resourceId: string;
  productId: string;
  requestId: string;
  /** JSON, as recorded. Empty before a creation. */
  before: string;
  after: string;
  createdAt: string | undefined;
}

export interface ListAuditLogRequest {
  /** Narrow to one resource, e.g. wallet_type + wty_…. */
  resourceType: string;
  resourceId: string;
  /** Or to one actor. */
  actorId: string;
  limit: number;
  /** next_cursor from the previous page; empty for the newest entries. */
  cursor: string;
}

export interface ListAuditLogResponse {
  /** Newest first. */
  entries: AuditEntry[];
  nextCursor: string;
}
