// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: proto/openpay/v1/ledger.proto

/* eslint-disable */

export const protobufPackage = "v1";

export enum LedgerAccountType {
  LEDGER_ACCOUNT_TYPE_UNSPECIFIED = "LEDGER_ACCOUNT_TYPE_UNSPECIFIED",
  LEDGER_ACCOUNT_TYPE_ASSET = "LEDGER_ACCOUNT_TYPE_ASSET",
  LEDGER_ACCOUNT_TYPE_LIABILITY = "LEDGER_ACCOUNT_TYPE_LIABILITY",
  LEDGER_ACCOUNT_TYPE_EQUITY = "LEDGER_ACCOUNT_TYPE_EQUITY",
  LEDGER_ACCOUNT_TYPE_INCOME = "LEDGER_ACCOUNT_TYPE_INCOME",
  LEDGER_ACCOUNT_TYPE_EXPENSE = "LEDGER_ACCOUNT_TYPE_EXPENSE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum PostingDirection {
  POSTING_DIRECTION_UNSPECIFIED = "POSTING_DIRECTION_UNSPECIFIED",
  POSTING_DIRECTION_DEBIT = "POSTING_DIRECTION_DEBIT",
  POSTING_DIRECTION_CREDIT = "POSTING_DIRECTION_CREDIT",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum LedgerCheckStatus {
  LEDGER_CHECK_STATUS_UNSPECIFIED = "LEDGER_CHECK_STATUS_UNSPECIFIED",
  /** LEDGER_CHECK_STATUS_OK - Every invariant held. */
  LEDGER_CHECK_STATUS_OK = "LEDGER_CHECK_STATUS_OK",
  /** LEDGER_CHECK_STATUS_DRIFT - At least one invariant was broken. Never fixed automatically. */
  LEDGER_CHECK_STATUS_DRIFT = "LEDGER_CHECK_STATUS_DRIFT",
  /** LEDGER_CHECK_STATUS_ERROR - The check itself could not complete, so nothing is known. */
  LEDGER_CHECK_STATUS_ERROR = "LEDGER_CHECK_STATUS_ERROR",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface LedgerBalance {
  /** What the account holds, in its natural direction. */
  balance: string;
  /** Reserved by active holds and not yet posted. */
  held: string;
  /** balance - held: what can still be spent. */
  available: string;
}

export interface LedgerAccount {
  id: string;
  /** e.g. income:zshala:product_sales, psp:razorpay:receivable. */
  code: string;
  /** Empty for platform accounts, which belong to no product. */
  productId: string;
  type: LedgerAccountType;
  currency: string;
  /** platform, customer, provider or merchant. */
  ownerKind: string;
  ownerId: string;
  allowNegative: boolean;
  /** active or closed. */
  status: string;
  balance: LedgerBalance | undefined;
  createdAt: string | undefined;
}

export interface GetLedgerAccountRequest {
  /** An account id (acc_…) or an account code (anything containing ':'). */
  id: string;
}

export interface GetLedgerAccountResponse {
  account: LedgerAccount | undefined;
}

export interface ListLedgerAccountsRequest {
  limit: number;
  offset: number;
  /** Only this product's accounts. */
  productId: string;
  /** Only accounts belonging to no product. Cannot be combined with product_id. */
  platformOnly: boolean;
  type: LedgerAccountType;
  /** Prefix of the account code, e.g. "psp:" or "income:zshala:". */
  codePrefix: string;
}

export interface ListLedgerAccountsResponse {
  accounts: LedgerAccount[];
  /** Size of the whole filtered set, not of this page. */
  total: string;
}

/**
 * One line of an account statement: a posting, with enough of its journal to
 * say why the money moved.
 */
export interface StatementEntry {
  journalId: string;
  journalExternalId: string;
  journalKind: string;
  memo: string;
  direction: PostingDirection;
  amount: string;
  /** Effect on this account's natural balance: positive when it grew. */
  change: string;
  /** The account's natural balance immediately after this posting. */
  balanceAfter: string;
  postedAt: string | undefined;
}

export interface GetAccountStatementRequest {
  /** An account id or code, as for GetLedgerAccount. */
  accountId: string;
  limit: number;
  /** next_cursor from the previous page. Empty for the newest entries. */
  cursor: string;
}

export interface GetAccountStatementResponse {
  account:
    | LedgerAccount
    | undefined;
  /** Newest first. */
  entries: StatementEntry[];
  /** Pass as cursor for the next, older page. Empty on the last page. */
  nextCursor: string;
}

export interface JournalPosting {
  accountId: string;
  accountCode: string;
  direction: PostingDirection;
  amount: string;
  currency: string;
}

export interface Journal {
  id: string;
  externalId: string;
  kind: string;
  productId: string;
  sourceKind: string;
  sourceId: string;
  /** The journal this one reverses, if it is a correction. */
  reversesJournalId: string;
  memo: string;
  postings: JournalPosting[];
  postedAt: string | undefined;
}

export interface GetJournalRequest {
  /** A journal id (jrn_…) or its external id (anything containing ':'). */
  id: string;
}

export interface GetJournalResponse {
  journal: Journal | undefined;
}

export interface TrialBalanceLine {
  accountId: string;
  accountCode: string;
  type: LedgerAccountType;
  productId: string;
  currency: string;
  debits: string;
  credits: string;
  /** debits - credits. */
  rawBalance: string;
  /** The balance in the account's natural direction. */
  balance: string;
}

export interface TrialBalanceTotal {
  currency: string;
  debits: string;
  credits: string;
  /**
   * For the whole platform this must be zero. For one product it generally is
   * not: the other side of its revenue sits in platform accounts.
   */
  difference: string;
}

export interface GetTrialBalanceRequest {
  /** Only this product's accounts. Empty for the whole platform. */
  productId: string;
  /** Balances as they stood at this moment. Empty for now. */
  asOf:
    | string
    | undefined;
  /** Include accounts that have never been posted to. */
  includeEmpty: boolean;
}

export interface GetTrialBalanceResponse {
  lines: TrialBalanceLine[];
  totals: TrialBalanceTotal[];
  asOf: string | undefined;
}

export interface LedgerCheckFinding {
  /** Which invariant, e.g. journal_unbalanced, balance_drift. */
  invariant: string;
  /** What it concerns: an account code, journal external id, or currency. */
  subject: string;
  expected: string;
  actual: string;
  detail: string;
}

export interface LedgerCheckRun {
  id: string;
  status: LedgerCheckStatus;
  /** scheduled or manual. */
  trigger: string;
  /** Who asked, for a manual run. */
  triggeredBy: string;
  findings: LedgerCheckFinding[];
  /** Set when the findings list was cut short; the ledger has more. */
  truncated: boolean;
  error: string;
  startedAt: string | undefined;
  finishedAt: string | undefined;
}

export interface RunLedgerCheckRequest {
}

export interface RunLedgerCheckResponse {
  run: LedgerCheckRun | undefined;
}

export interface ListLedgerCheckRunsRequest {
  limit: number;
}

export interface ListLedgerCheckRunsResponse {
  /** Newest first. */
  runs: LedgerCheckRun[];
}
