// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: proto/openpay/v1/me.proto

/* eslint-disable */
import type { Product } from "./product";

export const protobufPackage = "v1";

/**
 * GetMe tells the admin console who the operator is, what they may do, and
 * on which products — resolved by the server exactly as it resolves them for
 * every other call. The console uses it to shape navigation; the server
 * still checks every request, so hiding a button is never the boundary.
 */
export interface GetMeRequest {
}

export interface GetMeResponse {
  userId: string;
  /** The operator's OpenPay permissions, as opengate forwarded them. */
  permissions: string[];
  /**
   * True for central ops (openpay:scope:all): every product, plus the
   * platform-level screens.
   */
  scopeAll: boolean;
  /**
   * The products this operator may see: every product for central ops,
   * otherwise those their scope grants that exist.
   */
  products: Product[];
}
