// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: proto/openpay/v1/openpay.proto

/* eslint-disable */
import type { HttpBody } from "../../../google/api/httpbody";
import type {
  CreateServiceCredentialRequest,
  CreateServiceCredentialResponse,
  ListServiceCredentialsRequest,
  ListServiceCredentialsResponse,
  RevokeServiceCredentialRequest,
  RevokeServiceCredentialResponse,
} from "./credential";
import type {
  GetCustomerRequest,
  GetCustomerResponse,
  UpsertCustomerRequest,
  UpsertCustomerResponse,
} from "./customer";
import type {
  GetAccountStatementRequest,
  GetAccountStatementResponse,
  GetJournalRequest,
  GetJournalResponse,
  GetLedgerAccountRequest,
  GetLedgerAccountResponse,
  GetTrialBalanceRequest,
  GetTrialBalanceResponse,
  ListLedgerAccountsRequest,
  ListLedgerAccountsResponse,
  ListLedgerCheckRunsRequest,
  ListLedgerCheckRunsResponse,
  RunLedgerCheckRequest,
  RunLedgerCheckResponse,
} from "./ledger";
import type { GetMeRequest, GetMeResponse } from "./me";
import type {
  CancelOrderRequest,
  CancelOrderResponse,
  CreateItemRequest,
  CreateItemResponse,
  CreateOrderRequest,
  CreateOrderResponse,
  GetOrderRequest,
  GetOrderResponse,
  ListItemsRequest,
  ListItemsResponse,
  RefundOrderRequest,
  RefundOrderResponse,
} from "./order";
import type {
  CreatePaymentRequest,
  CreatePaymentResponse,
  CreateRefundRequest,
  CreateRefundResponse,
  GetDisputeRequest,
  GetDisputeResponse,
  GetPaymentRequest,
  GetPaymentResponse,
  GetRefundRequest,
  GetRefundResponse,
  ListDisputesRequest,
  ListDisputesResponse,
  ListPaymentsRequest,
  ListPaymentsResponse,
  ListRefundsRequest,
  ListRefundsResponse,
  SubmitDisputeEvidenceRequest,
  SubmitDisputeEvidenceResponse,
  SyncPaymentRequest,
  SyncPaymentResponse,
} from "./payment";
import type {
  CreateProductRequest,
  CreateProductResponse,
  GetProductRequest,
  GetProductResponse,
  ListProductsRequest,
  ListProductsResponse,
  UpdateProductRequest,
  UpdateProductResponse,
} from "./product";
import type {
  ListProvidersRequest,
  ListProvidersResponse,
  SetProviderOverrideRequest,
  SetProviderOverrideResponse,
} from "./provider";
import type {
  GetFeeVarianceRequest,
  GetFeeVarianceResponse,
  GetReconSummaryRequest,
  GetReconSummaryResponse,
  GetSettlementRequest,
  GetSettlementResponse,
  ListReconBreaksRequest,
  ListReconBreaksResponse,
  ListSettlementsRequest,
  ListSettlementsResponse,
  ResolveReconBreakRequest,
  ResolveReconBreakResponse,
  RunReconCycleRequest,
  RunReconCycleResponse,
} from "./recon";
import type {
  ExportAccountStatementRequest,
  ExportWalletStatementRequest,
  GetProductPnLRequest,
  GetProductPnLResponse,
  GetProviderStatsRequest,
  GetProviderStatsResponse,
} from "./report";
import type {
  AdjustWalletRequest,
  AdjustWalletResponse,
  GetFloatHeldRequest,
  GetFloatHeldResponse,
  GetWalletRequest,
  GetWalletResponse,
  GetWalletStatementRequest,
  GetWalletStatementResponse,
  GrantWalletRequest,
  GrantWalletResponse,
  ListCustomerWalletsRequest,
  ListCustomerWalletsResponse,
  OpenWalletRequest,
  OpenWalletResponse,
  TransferWalletRequest,
  TransferWalletResponse,
} from "./wallet";
import type {
  CreateWalletTypeRequest,
  CreateWalletTypeResponse,
  GetWalletTypeRequest,
  GetWalletTypeResponse,
  ListWalletTypesRequest,
  ListWalletTypesResponse,
  UpdateWalletTypeRequest,
  UpdateWalletTypeResponse,
} from "./wallet_type";
import type {
  AddBeneficiaryRequest,
  AddBeneficiaryResponse,
  DecideWithdrawalRequest,
  DecideWithdrawalResponse,
  GetWithdrawalRequest,
  GetWithdrawalResponse,
  ListBeneficiariesRequest,
  ListBeneficiariesResponse,
  ListWithdrawalsRequest,
  ListWithdrawalsResponse,
  RequestWithdrawalRequest,
  RequestWithdrawalResponse,
} from "./withdrawal";

export const protobufPackage = "v1";

/**
 * Liveness and readiness are served outside this API, at /healthz and /readyz.
 * They are deliberately not RPCs: probes should not sit in the versioned,
 * publicly routed surface of a payments API.
 */
export interface OpenPay {
  CreateProduct(request: CreateProductRequest): Promise<CreateProductResponse>;
  GetProduct(request: GetProductRequest): Promise<GetProductResponse>;
  ListProducts(request: ListProductsRequest): Promise<ListProductsResponse>;
  UpdateProduct(request: UpdateProductRequest): Promise<UpdateProductResponse>;
  CreateServiceCredential(request: CreateServiceCredentialRequest): Promise<CreateServiceCredentialResponse>;
  ListServiceCredentials(request: ListServiceCredentialsRequest): Promise<ListServiceCredentialsResponse>;
  RevokeServiceCredential(request: RevokeServiceCredentialRequest): Promise<RevokeServiceCredentialResponse>;
  CreateWalletType(request: CreateWalletTypeRequest): Promise<CreateWalletTypeResponse>;
  GetWalletType(request: GetWalletTypeRequest): Promise<GetWalletTypeResponse>;
  ListWalletTypes(request: ListWalletTypesRequest): Promise<ListWalletTypesResponse>;
  UpdateWalletType(request: UpdateWalletTypeRequest): Promise<UpdateWalletTypeResponse>;
  UpsertCustomer(request: UpsertCustomerRequest): Promise<UpsertCustomerResponse>;
  GetCustomer(request: GetCustomerRequest): Promise<GetCustomerResponse>;
  GetLedgerAccount(request: GetLedgerAccountRequest): Promise<GetLedgerAccountResponse>;
  ListLedgerAccounts(request: ListLedgerAccountsRequest): Promise<ListLedgerAccountsResponse>;
  GetAccountStatement(request: GetAccountStatementRequest): Promise<GetAccountStatementResponse>;
  GetJournal(request: GetJournalRequest): Promise<GetJournalResponse>;
  GetTrialBalance(request: GetTrialBalanceRequest): Promise<GetTrialBalanceResponse>;
  RunLedgerCheck(request: RunLedgerCheckRequest): Promise<RunLedgerCheckResponse>;
  ListLedgerCheckRuns(request: ListLedgerCheckRunsRequest): Promise<ListLedgerCheckRunsResponse>;
  OpenWallet(request: OpenWalletRequest): Promise<OpenWalletResponse>;
  GetWallet(request: GetWalletRequest): Promise<GetWalletResponse>;
  ListCustomerWallets(request: ListCustomerWalletsRequest): Promise<ListCustomerWalletsResponse>;
  GetWalletStatement(request: GetWalletStatementRequest): Promise<GetWalletStatementResponse>;
  GrantWallet(request: GrantWalletRequest): Promise<GrantWalletResponse>;
  TransferWallet(request: TransferWalletRequest): Promise<TransferWalletResponse>;
  AdjustWallet(request: AdjustWalletRequest): Promise<AdjustWalletResponse>;
  GetFloatHeld(request: GetFloatHeldRequest): Promise<GetFloatHeldResponse>;
  CreatePayment(request: CreatePaymentRequest): Promise<CreatePaymentResponse>;
  GetPayment(request: GetPaymentRequest): Promise<GetPaymentResponse>;
  ListPayments(request: ListPaymentsRequest): Promise<ListPaymentsResponse>;
  SyncPayment(request: SyncPaymentRequest): Promise<SyncPaymentResponse>;
  CreateRefund(request: CreateRefundRequest): Promise<CreateRefundResponse>;
  GetRefund(request: GetRefundRequest): Promise<GetRefundResponse>;
  ListRefunds(request: ListRefundsRequest): Promise<ListRefundsResponse>;
  GetDispute(request: GetDisputeRequest): Promise<GetDisputeResponse>;
  ListDisputes(request: ListDisputesRequest): Promise<ListDisputesResponse>;
  SubmitDisputeEvidence(request: SubmitDisputeEvidenceRequest): Promise<SubmitDisputeEvidenceResponse>;
  CreateItem(request: CreateItemRequest): Promise<CreateItemResponse>;
  ListItems(request: ListItemsRequest): Promise<ListItemsResponse>;
  CreateOrder(request: CreateOrderRequest): Promise<CreateOrderResponse>;
  GetOrder(request: GetOrderRequest): Promise<GetOrderResponse>;
  RefundOrder(request: RefundOrderRequest): Promise<RefundOrderResponse>;
  ListSettlements(request: ListSettlementsRequest): Promise<ListSettlementsResponse>;
  GetSettlement(request: GetSettlementRequest): Promise<GetSettlementResponse>;
  ListReconBreaks(request: ListReconBreaksRequest): Promise<ListReconBreaksResponse>;
  ResolveReconBreak(request: ResolveReconBreakRequest): Promise<ResolveReconBreakResponse>;
  GetReconSummary(request: GetReconSummaryRequest): Promise<GetReconSummaryResponse>;
  RunReconCycle(request: RunReconCycleRequest): Promise<RunReconCycleResponse>;
  GetFeeVariance(request: GetFeeVarianceRequest): Promise<GetFeeVarianceResponse>;
  AddBeneficiary(request: AddBeneficiaryRequest): Promise<AddBeneficiaryResponse>;
  ListBeneficiaries(request: ListBeneficiariesRequest): Promise<ListBeneficiariesResponse>;
  RequestWithdrawal(request: RequestWithdrawalRequest): Promise<RequestWithdrawalResponse>;
  ApproveWithdrawal(request: DecideWithdrawalRequest): Promise<DecideWithdrawalResponse>;
  RejectWithdrawal(request: DecideWithdrawalRequest): Promise<DecideWithdrawalResponse>;
  GetWithdrawal(request: GetWithdrawalRequest): Promise<GetWithdrawalResponse>;
  ListWithdrawals(request: ListWithdrawalsRequest): Promise<ListWithdrawalsResponse>;
  CancelOrder(request: CancelOrderRequest): Promise<CancelOrderResponse>;
  ListProviders(request: ListProvidersRequest): Promise<ListProvidersResponse>;
  SetProviderOverride(request: SetProviderOverrideRequest): Promise<SetProviderOverrideResponse>;
  GetProductPnL(request: GetProductPnLRequest): Promise<GetProductPnLResponse>;
  GetProviderStats(request: GetProviderStatsRequest): Promise<GetProviderStatsResponse>;
  ExportAccountStatement(request: ExportAccountStatementRequest): Promise<HttpBody>;
  ExportWalletStatement(request: ExportWalletStatementRequest): Promise<HttpBody>;
  GetMe(request: GetMeRequest): Promise<GetMeResponse>;
}
