// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: proto/openpay/v1/order.proto

/* eslint-disable */

export const protobufPackage = "v1";

export enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = "ORDER_STATUS_UNSPECIFIED",
  /** ORDER_STATUS_PENDING_PAYMENT - Waiting for the card share; wallet shares are held. */
  ORDER_STATUS_PENDING_PAYMENT = "ORDER_STATUS_PENDING_PAYMENT",
  ORDER_STATUS_PAID = "ORDER_STATUS_PAID",
  ORDER_STATUS_FAILED = "ORDER_STATUS_FAILED",
  ORDER_STATUS_CANCELLED = "ORDER_STATUS_CANCELLED",
  ORDER_STATUS_PARTIALLY_REFUNDED = "ORDER_STATUS_PARTIALLY_REFUNDED",
  ORDER_STATUS_REFUNDED = "ORDER_STATUS_REFUNDED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface Item {
  id: string;
  code: string;
  name: string;
  /** For description and reporting only; an order carries what was charged. */
  referencePrice: string;
  currency: string;
  /** A reporting label, e.g. gst_18. Never used to compute anything. */
  taxClass: string;
  createdAt: string | undefined;
}

export interface CreateItemRequest {
  code: string;
  name: string;
  referencePrice: string;
  currency: string;
  taxClass: string;
}

export interface CreateItemResponse {
  item: Item | undefined;
}

export interface ListItemsRequest {
}

export interface ListItemsResponse {
  items: Item[];
}

export interface OrderLine {
  /** Optional: a catalogue item of this product. */
  itemId: string;
  description: string;
  quantity: number;
  unitAmount: string;
  amount: string;
}

export interface WalletTender {
  walletId: string;
  amount: string;
}

export interface OrderTender {
  /** wallet or gateway. */
  kind: string;
  walletId: string;
  amount: string;
  /** held, captured or released. */
  status: string;
}

export interface Order {
  id: string;
  externalRef: string;
  invoiceRef: string;
  productId: string;
  customerId: string;
  currency: string;
  subtotal: string;
  discount: string;
  tax: string;
  total: string;
  taxRate: string;
  /** False when the product sent a bare total: booked gross, flagged here. */
  taxBreakdownProvided: boolean;
  status: OrderStatus;
  failureReason: string;
  lines: OrderLine[];
  tenders: OrderTender[];
  /** The card share, and where to send the customer to pay it. */
  gatewayAmount: string;
  paymentId: string;
  checkoutUrl: string;
  expiresAt: string | undefined;
  paidAt: string | undefined;
  createdAt: string | undefined;
  refunds: OrderRefund[];
}

/**
 * An order refund carries its own tax split (plan.md D13). Without one, the
 * split is proportional to the order's and tax_breakdown_provided is false.
 */
export interface OrderRefund {
  id: string;
  amount: string;
  subtotal: string;
  discount: string;
  tax: string;
  taxBreakdownProvided: boolean;
  /** source or wallet. */
  destination: string;
  reasonCode: string;
  memo: string;
  parts: OrderRefundPart[];
  createdAt: string | undefined;
}

/** How much of a refund went back through one tender, and where. */
export interface OrderRefundPart {
  amount: string;
  /** Credited to this wallet… */
  walletId: string;
  /** …or returned to the card through this payment refund. */
  refundId: string;
}

export interface RefundOrderRequest {
  id: string;
  amount: string;
  /** The refund's own split. Leave false to have it split proportionally. */
  taxBreakdownProvided: boolean;
  subtotal: string;
  discount: string;
  tax: string;
  /** Empty uses the product's default. */
  destination: string;
  reasonCode: string;
  memo: string;
}

export interface RefundOrderResponse {
  order: Order | undefined;
  refund: OrderRefund | undefined;
}

/**
 * CreateOrderRequest records a purchase and starts paying for it. Called by
 * a product backend with an Idempotency-Key; also idempotent on external_ref.
 */
export interface CreateOrderRequest {
  /** The product's own order id. */
  externalRef: string;
  invoiceRef: string;
  /** Optional for a card-only guest purchase; required to pay from wallets. */
  customerId: string;
  currency: string;
  /**
   * With tax_breakdown_provided, subtotal - discount + tax must equal total.
   * Without it, send only total: it is booked gross and flagged.
   */
  taxBreakdownProvided: boolean;
  subtotal: string;
  discount: string;
  tax: string;
  total: string;
  taxRate: string;
  /** If given, they must sum to the subtotal. */
  lines: OrderLine[];
  /**
   * Explicit wallet shares. Or auto_tender: draw from the customer's wallets,
   * granted value first. A card pays whatever remains.
   */
  walletTenders: WalletTender[];
  autoTender: boolean;
  description: string;
  returnUrl: string;
}

export interface CreateOrderResponse {
  order: Order | undefined;
}

export interface GetOrderRequest {
  id: string;
}

export interface GetOrderResponse {
  order: Order | undefined;
}

export interface CancelOrderRequest {
  id: string;
  reason: string;
}

export interface CancelOrderResponse {
  order: Order | undefined;
}

export interface ListOrdersRequest {
  productId: string;
  customerId: string;
  status: OrderStatus;
  limit: number;
  offset: number;
}

export interface ListOrdersResponse {
  /** Newest first. Summaries: lines, tenders and refunds come with GetOrder. */
  orders: Order[];
  total: string;
}
