// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: proto/openpay/v1/wallet.proto

/* eslint-disable */
import type { LedgerBalance, PostingDirection, StatementEntry } from "./ledger";

export const protobufPackage = "v1";

export enum WalletStatus {
  WALLET_STATUS_UNSPECIFIED = "WALLET_STATUS_UNSPECIFIED",
  WALLET_STATUS_ACTIVE = "WALLET_STATUS_ACTIVE",
  /** WALLET_STATUS_FROZEN - Customer-initiated movement is refused while support investigates. */
  WALLET_STATUS_FROZEN = "WALLET_STATUS_FROZEN",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface Wallet {
  id: string;
  customerId: string;
  walletTypeId: string;
  /** e.g. MAIN, BONUS. */
  walletTypeCode: string;
  /** Empty for a platform-scoped wallet, spendable in every product. */
  productId: string;
  currency: string;
  status: WalletStatus;
  balance: LedgerBalance | undefined;
  createdAt: string | undefined;
}

/**
 * OpenWallet returns a customer's wallet of a type, creating it on first
 * reference. Called by a product backend. Naturally idempotent on (customer,
 * type), so it takes no Idempotency-Key.
 */
export interface OpenWalletRequest {
  customerId: string;
  /** The caller's own product's type, or a platform-scoped type. */
  walletTypeCode: string;
}

export interface OpenWalletResponse {
  wallet:
    | Wallet
    | undefined;
  /** False when the wallet already existed. */
  created: boolean;
}

export interface GetWalletRequest {
  id: string;
}

export interface GetWalletResponse {
  wallet: Wallet | undefined;
}

export interface ListCustomerWalletsRequest {
  customerId: string;
}

export interface ListCustomerWalletsResponse {
  wallets: Wallet[];
}

export interface GetWalletStatementRequest {
  walletId: string;
  limit: number;
  /** next_cursor from the previous page. Empty for the newest entries. */
  cursor: string;
}

export interface GetWalletStatementResponse {
  wallet:
    | Wallet
    | undefined;
  /** Newest first; change is positive when the wallet grew. */
  entries: StatementEntry[];
  nextCursor: string;
}

export interface GrantWalletRequest {
  walletId: string;
  amount: string;
  /** promotion, referral, cashback, loyalty or compensation. */
  reasonCode: string;
  memo: string;
  /**
   * Whose promotions budget pays, for a platform-scoped wallet. Ignored for a
   * product wallet (its own product pays) and for a product backend (the
   * caller's product pays).
   */
  fundingProductId: string;
}

export interface GrantWalletResponse {
  wallet: Wallet | undefined;
  journalId: string;
}

export interface TransferWalletRequest {
  fromWalletId: string;
  /** The recipient's wallet of the same type is opened if they have none. */
  toCustomerId: string;
  amount: string;
}

export interface TransferWalletResponse {
  from: Wallet | undefined;
  to: Wallet | undefined;
  journalId: string;
}

export interface AdjustWalletRequest {
  walletId: string;
  amount: string;
  /** CREDIT adds value to the wallet; DEBIT removes it. */
  direction: PostingDirection;
  /** goodwill, error_correction, fraud_recovery or migration. */
  reasonCode: string;
  /** Required: an adjustment nobody explained cannot be audited. */
  memo: string;
  /** Whose adjustments account funds it, for a platform-scoped wallet. */
  productId: string;
}

export interface AdjustWalletResponse {
  wallet: Wallet | undefined;
  journalId: string;
}

/**
 * FloatHeld is the real customer money held — the balance of fundable
 * wallets only; granted value is excluded because nobody paid for it.
 */
export interface FloatHeldLine {
  /** Empty for platform-scoped wallets, which belong to no one product. */
  productId: string;
  currency: string;
  amount: string;
  wallets: string;
}

export interface GetFloatHeldRequest {
}

export interface GetFloatHeldResponse {
  lines: FloatHeldLine[];
  asOf: string | undefined;
}
