// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: proto/openpay/v1/wallet_type.proto

/* eslint-disable */

export const protobufPackage = "v1";

export enum WalletScope {
  WALLET_SCOPE_UNSPECIFIED = "WALLET_SCOPE_UNSPECIFIED",
  /** WALLET_SCOPE_PRODUCT - Confined to one product. */
  WALLET_SCOPE_PRODUCT = "WALLET_SCOPE_PRODUCT",
  /**
   * WALLET_SCOPE_PLATFORM - Spendable across every product — possible only because this is a
   * single-tenant estate.
   */
  WALLET_SCOPE_PLATFORM = "WALLET_SCOPE_PLATFORM",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ExpiryPolicy {
  EXPIRY_POLICY_UNSPECIFIED = "EXPIRY_POLICY_UNSPECIFIED",
  EXPIRY_POLICY_NONE = "EXPIRY_POLICY_NONE",
  /** EXPIRY_POLICY_FIXED - Expires a fixed period after the balance was credited. */
  EXPIRY_POLICY_FIXED = "EXPIRY_POLICY_FIXED",
  /** EXPIRY_POLICY_ROLLING - Pushes expiry out on every use. */
  EXPIRY_POLICY_ROLLING = "EXPIRY_POLICY_ROLLING",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum WalletTypeStatus {
  WALLET_TYPE_STATUS_UNSPECIFIED = "WALLET_TYPE_STATUS_UNSPECIFIED",
  WALLET_TYPE_STATUS_ACTIVE = "WALLET_TYPE_STATUS_ACTIVE",
  /**
   * WALLET_TYPE_STATUS_ARCHIVED - Stops new wallets being created. Existing ones keep working: they hold
   * real balances.
   */
  WALLET_TYPE_STATUS_ARCHIVED = "WALLET_TYPE_STATUS_ARCHIVED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/**
 * WalletCapabilities is what a balance of this type is allowed to do.
 *
 * fundable and grantable are deliberately separate. Money a customer paid for
 * is a real liability; a promotional coin we issued is funded from marketing
 * spend, expires, and should never be cashable. Mixing them in one balance
 * permanently loses the answer to "how much real customer money do we hold?".
 */
export interface WalletCapabilities {
  /** May be topped up with real money. */
  fundable: boolean;
  /** May be credited without payment, as a promotion. */
  grantable: boolean;
  /**
   * May be cashed out to a bank. Requires an approval reference: enabling this
   * moves the company from closed-loop into prepaid-instrument territory.
   */
  withdrawable: boolean;
  /** May be transferred to another customer. */
  transferable: boolean;
  /** Refunds may be routed here. */
  refundableToSource: boolean;
  /** May go negative. Off unless a product genuinely needs overdraft. */
  allowNegative: boolean;
}

/** WalletLimits are in minor units. Zero means no limit. */
export interface WalletLimits {
  maxBalance: string;
  maxTxnAmount: string;
  dailyLoadLimit: string;
  /**
   * Withdrawal policy, for withdrawable types only (rejected otherwise).
   * The smallest withdrawal accepted; smaller requests are refused.
   */
  minWithdrawalAmount: string;
  /**
   * Withdrawals up to this amount are paid out automatically; larger ones
   * wait for an approver other than the requester. Zero: none need approval.
   */
  withdrawalApprovalThreshold: string;
  /** The most one wallet may cash out per day (Indian day). Zero: no limit. */
  dailyWithdrawalLimit: string;
}

/** WithdrawalApproval records who signed off on enabling withdrawal. */
export interface WithdrawalApproval {
  approvedBy: string;
  approvedAt: string | undefined;
  reference: string;
}

export interface WalletType {
  id: string;
  /** Empty for platform-scoped types. */
  productId: string;
  scope: WalletScope;
  code: string;
  name: string;
  currency: string;
  capabilities: WalletCapabilities | undefined;
  expiryPolicy: ExpiryPolicy;
  expiryDays: number;
  limits: WalletLimits | undefined;
  status: WalletTypeStatus;
  withdrawalApproval: WithdrawalApproval | undefined;
  createdAt: string | undefined;
  updatedAt: string | undefined;
}

export interface CreateWalletTypeRequest {
  /** Leave empty to create a platform-scoped type spendable everywhere. */
  productId: string;
  code: string;
  name: string;
  currency: string;
  capabilities: WalletCapabilities | undefined;
  expiryPolicy: ExpiryPolicy;
  /** Required when expiry_policy is not NONE, and rejected when it is. */
  expiryDays: number;
  limits:
    | WalletLimits
    | undefined;
  /**
   * Required when capabilities.withdrawable is set: the compliance sign-off
   * this configuration rests on.
   */
  withdrawalApprovalRef: string;
}

export interface CreateWalletTypeResponse {
  walletType: WalletType | undefined;
}

export interface GetWalletTypeRequest {
  id: string;
}

export interface GetWalletTypeResponse {
  walletType: WalletType | undefined;
}

export interface ListWalletTypesRequest {
  /**
   * The product whose wallet types to list. Platform-scoped types are always
   * included, since they are spendable there too.
   */
  productId: string;
}

export interface ListWalletTypesResponse {
  walletTypes: WalletType[];
}

/**
 * UpdateWalletTypeRequest carries only what stays safe to change once wallets
 * exist. Currency, scope and capabilities are absent on purpose: a balance
 * already held under one set of rules must not have them rewritten underneath
 * it.
 */
export interface UpdateWalletTypeRequest {
  id: string;
  name: string;
  status: WalletTypeStatus;
  limits: WalletLimits | undefined;
}

export interface UpdateWalletTypeResponse {
  walletType: WalletType | undefined;
}
