// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: proto/openpay/v1/withdrawal.proto

/* eslint-disable */

export const protobufPackage = "v1";

export enum WithdrawalStatus {
  WITHDRAWAL_STATUS_UNSPECIFIED = "WITHDRAWAL_STATUS_UNSPECIFIED",
  /** WITHDRAWAL_STATUS_PENDING_APPROVAL - Above the wallet type's threshold: waiting for an approver. */
  WITHDRAWAL_STATUS_PENDING_APPROVAL = "WITHDRAWAL_STATUS_PENDING_APPROVAL",
  /** WITHDRAWAL_STATUS_APPROVED - Cleared to send; the provider has not yet confirmed it. */
  WITHDRAWAL_STATUS_APPROVED = "WITHDRAWAL_STATUS_APPROVED",
  WITHDRAWAL_STATUS_PROCESSING = "WITHDRAWAL_STATUS_PROCESSING",
  WITHDRAWAL_STATUS_PAID = "WITHDRAWAL_STATUS_PAID",
  /** WITHDRAWAL_STATUS_FAILED - Never left; the money is back in the wallet. */
  WITHDRAWAL_STATUS_FAILED = "WITHDRAWAL_STATUS_FAILED",
  WITHDRAWAL_STATUS_REJECTED = "WITHDRAWAL_STATUS_REJECTED",
  /** WITHDRAWAL_STATUS_REVERSED - Left, then bounced; the money is back in the wallet. */
  WITHDRAWAL_STATUS_REVERSED = "WITHDRAWAL_STATUS_REVERSED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface Beneficiary {
  id: string;
  customerId: string;
  /** bank_account or vpa. */
  kind: string;
  name: string;
  /** Only the last four digits are ever returned. */
  accountNumberMasked: string;
  ifsc: string;
  vpa: string;
  /** pending, verified or failed. */
  status: string;
  /** The name the bank or UPI directory reports, to check against name. */
  nameAtBank: string;
  failureReason: string;
  verifiedAt: string | undefined;
  createdAt: string | undefined;
}

/**
 * AddBeneficiaryRequest registers a destination, verified with the provider
 * (penny drop / VPA lookup) before it can receive money.
 */
export interface AddBeneficiaryRequest {
  customerId: string;
  kind: string;
  name: string;
  accountNumber: string;
  ifsc: string;
  vpa: string;
}

export interface AddBeneficiaryResponse {
  beneficiary: Beneficiary | undefined;
}

export interface ListBeneficiariesRequest {
  customerId: string;
}

export interface ListBeneficiariesResponse {
  beneficiaries: Beneficiary[];
}

export interface Withdrawal {
  id: string;
  walletId: string;
  beneficiaryId: string;
  amount: string;
  currency: string;
  status: WithdrawalStatus;
  requiresApproval: boolean;
  requestedBy: string;
  decidedBy: string;
  decidedAt: string | undefined;
  decisionNote: string;
  failureReason: string;
  paidAt: string | undefined;
  createdAt: string | undefined;
}

/**
 * RequestWithdrawalRequest takes the amount out of the wallet at once. Up to
 * the wallet type's approval threshold it is sent immediately; above it, it
 * waits for approval. Requires an Idempotency-Key.
 */
export interface RequestWithdrawalRequest {
  walletId: string;
  beneficiaryId: string;
  amount: string;
}

export interface RequestWithdrawalResponse {
  withdrawal: Withdrawal | undefined;
}

export interface DecideWithdrawalRequest {
  id: string;
  /** Why. Required: a decision nobody explained cannot be audited. */
  note: string;
}

export interface DecideWithdrawalResponse {
  withdrawal: Withdrawal | undefined;
}

export interface GetWithdrawalRequest {
  id: string;
}

export interface GetWithdrawalResponse {
  withdrawal: Withdrawal | undefined;
}

export interface ListWithdrawalsRequest {
  /** WITHDRAWAL_STATUS_PENDING_APPROVAL gives the approval queue. */
  status: WithdrawalStatus;
  customerId: string;
  limit: number;
}

export interface ListWithdrawalsResponse {
  withdrawals: Withdrawal[];
}
