// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/openpay/v1/credential.proto

package openpay_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ServiceCredential with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ServiceCredential) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServiceCredential with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ServiceCredentialMultiError, or nil if none found.
func (m *ServiceCredential) ValidateAll() error {
	return m.validate(true)
}

func (m *ServiceCredential) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ProductId

	// no validation rules for Name

	// no validation rules for KeyId

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetLastUsedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ServiceCredentialValidationError{
					field:  "LastUsedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ServiceCredentialValidationError{
					field:  "LastUsedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastUsedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ServiceCredentialValidationError{
				field:  "LastUsedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetRevokedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ServiceCredentialValidationError{
					field:  "RevokedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ServiceCredentialValidationError{
					field:  "RevokedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRevokedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ServiceCredentialValidationError{
				field:  "RevokedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ServiceCredentialValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ServiceCredentialValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ServiceCredentialValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ServiceCredentialMultiError(errors)
	}

	return nil
}

// ServiceCredentialMultiError is an error wrapping multiple validation errors
// returned by ServiceCredential.ValidateAll() if the designated constraints
// aren't met.
type ServiceCredentialMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServiceCredentialMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServiceCredentialMultiError) AllErrors() []error { return m }

// ServiceCredentialValidationError is the validation error returned by
// ServiceCredential.Validate if the designated constraints aren't met.
type ServiceCredentialValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServiceCredentialValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServiceCredentialValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServiceCredentialValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServiceCredentialValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServiceCredentialValidationError) ErrorName() string {
	return "ServiceCredentialValidationError"
}

// Error satisfies the builtin error interface
func (e ServiceCredentialValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServiceCredential.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServiceCredentialValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServiceCredentialValidationError{}

// Validate checks the field values on CreateServiceCredentialRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateServiceCredentialRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateServiceCredentialRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateServiceCredentialRequestMultiError, or nil if none found.
func (m *CreateServiceCredentialRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateServiceCredentialRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProductId()) < 1 {
		err := CreateServiceCredentialRequestValidationError{
			field:  "ProductId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 100 {
		err := CreateServiceCredentialRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateServiceCredentialRequestMultiError(errors)
	}

	return nil
}

// CreateServiceCredentialRequestMultiError is an error wrapping multiple
// validation errors returned by CreateServiceCredentialRequest.ValidateAll()
// if the designated constraints aren't met.
type CreateServiceCredentialRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateServiceCredentialRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateServiceCredentialRequestMultiError) AllErrors() []error { return m }

// CreateServiceCredentialRequestValidationError is the validation error
// returned by CreateServiceCredentialRequest.Validate if the designated
// constraints aren't met.
type CreateServiceCredentialRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateServiceCredentialRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateServiceCredentialRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateServiceCredentialRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateServiceCredentialRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateServiceCredentialRequestValidationError) ErrorName() string {
	return "CreateServiceCredentialRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateServiceCredentialRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateServiceCredentialRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateServiceCredentialRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateServiceCredentialRequestValidationError{}

// Validate checks the field values on CreateServiceCredentialResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateServiceCredentialResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateServiceCredentialResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateServiceCredentialResponseMultiError, or nil if none found.
func (m *CreateServiceCredentialResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateServiceCredentialResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCredential()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateServiceCredentialResponseValidationError{
					field:  "Credential",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateServiceCredentialResponseValidationError{
					field:  "Credential",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCredential()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateServiceCredentialResponseValidationError{
				field:  "Credential",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Secret

	if len(errors) > 0 {
		return CreateServiceCredentialResponseMultiError(errors)
	}

	return nil
}

// CreateServiceCredentialResponseMultiError is an error wrapping multiple
// validation errors returned by CreateServiceCredentialResponse.ValidateAll()
// if the designated constraints aren't met.
type CreateServiceCredentialResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateServiceCredentialResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateServiceCredentialResponseMultiError) AllErrors() []error { return m }

// CreateServiceCredentialResponseValidationError is the validation error
// returned by CreateServiceCredentialResponse.Validate if the designated
// constraints aren't met.
type CreateServiceCredentialResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateServiceCredentialResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateServiceCredentialResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateServiceCredentialResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateServiceCredentialResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateServiceCredentialResponseValidationError) ErrorName() string {
	return "CreateServiceCredentialResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateServiceCredentialResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateServiceCredentialResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateServiceCredentialResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateServiceCredentialResponseValidationError{}

// Validate checks the field values on ListServiceCredentialsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListServiceCredentialsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListServiceCredentialsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListServiceCredentialsRequestMultiError, or nil if none found.
func (m *ListServiceCredentialsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListServiceCredentialsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProductId()) < 1 {
		err := ListServiceCredentialsRequestValidationError{
			field:  "ProductId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListServiceCredentialsRequestMultiError(errors)
	}

	return nil
}

// ListServiceCredentialsRequestMultiError is an error wrapping multiple
// validation errors returned by ListServiceCredentialsRequest.ValidateAll()
// if the designated constraints aren't met.
type ListServiceCredentialsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListServiceCredentialsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListServiceCredentialsRequestMultiError) AllErrors() []error { return m }

// ListServiceCredentialsRequestValidationError is the validation error
// returned by ListServiceCredentialsRequest.Validate if the designated
// constraints aren't met.
type ListServiceCredentialsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListServiceCredentialsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListServiceCredentialsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListServiceCredentialsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListServiceCredentialsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListServiceCredentialsRequestValidationError) ErrorName() string {
	return "ListServiceCredentialsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListServiceCredentialsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListServiceCredentialsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListServiceCredentialsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListServiceCredentialsRequestValidationError{}

// Validate checks the field values on ListServiceCredentialsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListServiceCredentialsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListServiceCredentialsResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListServiceCredentialsResponseMultiError, or nil if none found.
func (m *ListServiceCredentialsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListServiceCredentialsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetCredentials() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListServiceCredentialsResponseValidationError{
						field:  fmt.Sprintf("Credentials[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListServiceCredentialsResponseValidationError{
						field:  fmt.Sprintf("Credentials[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListServiceCredentialsResponseValidationError{
					field:  fmt.Sprintf("Credentials[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListServiceCredentialsResponseMultiError(errors)
	}

	return nil
}

// ListServiceCredentialsResponseMultiError is an error wrapping multiple
// validation errors returned by ListServiceCredentialsResponse.ValidateAll()
// if the designated constraints aren't met.
type ListServiceCredentialsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListServiceCredentialsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListServiceCredentialsResponseMultiError) AllErrors() []error { return m }

// ListServiceCredentialsResponseValidationError is the validation error
// returned by ListServiceCredentialsResponse.Validate if the designated
// constraints aren't met.
type ListServiceCredentialsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListServiceCredentialsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListServiceCredentialsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListServiceCredentialsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListServiceCredentialsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListServiceCredentialsResponseValidationError) ErrorName() string {
	return "ListServiceCredentialsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListServiceCredentialsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListServiceCredentialsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListServiceCredentialsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListServiceCredentialsResponseValidationError{}

// Validate checks the field values on RevokeServiceCredentialRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RevokeServiceCredentialRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RevokeServiceCredentialRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// RevokeServiceCredentialRequestMultiError, or nil if none found.
func (m *RevokeServiceCredentialRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RevokeServiceCredentialRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := RevokeServiceCredentialRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RevokeServiceCredentialRequestMultiError(errors)
	}

	return nil
}

// RevokeServiceCredentialRequestMultiError is an error wrapping multiple
// validation errors returned by RevokeServiceCredentialRequest.ValidateAll()
// if the designated constraints aren't met.
type RevokeServiceCredentialRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevokeServiceCredentialRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevokeServiceCredentialRequestMultiError) AllErrors() []error { return m }

// RevokeServiceCredentialRequestValidationError is the validation error
// returned by RevokeServiceCredentialRequest.Validate if the designated
// constraints aren't met.
type RevokeServiceCredentialRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevokeServiceCredentialRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevokeServiceCredentialRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevokeServiceCredentialRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevokeServiceCredentialRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevokeServiceCredentialRequestValidationError) ErrorName() string {
	return "RevokeServiceCredentialRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RevokeServiceCredentialRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevokeServiceCredentialRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevokeServiceCredentialRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevokeServiceCredentialRequestValidationError{}

// Validate checks the field values on RevokeServiceCredentialResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RevokeServiceCredentialResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RevokeServiceCredentialResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// RevokeServiceCredentialResponseMultiError, or nil if none found.
func (m *RevokeServiceCredentialResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RevokeServiceCredentialResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCredential()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RevokeServiceCredentialResponseValidationError{
					field:  "Credential",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RevokeServiceCredentialResponseValidationError{
					field:  "Credential",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCredential()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RevokeServiceCredentialResponseValidationError{
				field:  "Credential",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RevokeServiceCredentialResponseMultiError(errors)
	}

	return nil
}

// RevokeServiceCredentialResponseMultiError is an error wrapping multiple
// validation errors returned by RevokeServiceCredentialResponse.ValidateAll()
// if the designated constraints aren't met.
type RevokeServiceCredentialResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevokeServiceCredentialResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevokeServiceCredentialResponseMultiError) AllErrors() []error { return m }

// RevokeServiceCredentialResponseValidationError is the validation error
// returned by RevokeServiceCredentialResponse.Validate if the designated
// constraints aren't met.
type RevokeServiceCredentialResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevokeServiceCredentialResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevokeServiceCredentialResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevokeServiceCredentialResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevokeServiceCredentialResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevokeServiceCredentialResponseValidationError) ErrorName() string {
	return "RevokeServiceCredentialResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RevokeServiceCredentialResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevokeServiceCredentialResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevokeServiceCredentialResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevokeServiceCredentialResponseValidationError{}
