// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/openpay/v1/credential.proto

package openpay_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialStatus int32

const (
	CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED CredentialStatus = 0
	CredentialStatus_CREDENTIAL_STATUS_ACTIVE      CredentialStatus = 1
	CredentialStatus_CREDENTIAL_STATUS_REVOKED     CredentialStatus = 2
)

// Enum value maps for CredentialStatus.
var (
	CredentialStatus_name = map[int32]string{
		0: "CREDENTIAL_STATUS_UNSPECIFIED",
		1: "CREDENTIAL_STATUS_ACTIVE",
		2: "CREDENTIAL_STATUS_REVOKED",
	}
	CredentialStatus_value = map[string]int32{
		"CREDENTIAL_STATUS_UNSPECIFIED": 0,
		"CREDENTIAL_STATUS_ACTIVE":      1,
		"CREDENTIAL_STATUS_REVOKED":     2,
	}
)

func (x CredentialStatus) Enum() *CredentialStatus {
	p := new(CredentialStatus)
	*p = x
	return p
}

func (x CredentialStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_openpay_v1_credential_proto_enumTypes[0].Descriptor()
}

func (CredentialStatus) Type() protoreflect.EnumType {
	return &file_proto_openpay_v1_credential_proto_enumTypes[0]
}

func (x CredentialStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialStatus.Descriptor instead.
func (CredentialStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_openpay_v1_credential_proto_rawDescGZIP(), []int{0}
}

// ServiceCredential is how a product's backend authenticates. It never carries
// the secret: that exists only in the response to CreateServiceCredential.
type ServiceCredential struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The public half, safe to display and to log.
	KeyId  string           `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Status CredentialStatus `protobuf:"varint,5,opt,name=status,proto3,enum=v1.CredentialStatus" json:"status,omitempty"`
	// Answers "is anyone still using this key?" before revoking it.
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceCredential) Reset() {
	*x = ServiceCredential{}
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCredential) ProtoMessage() {}

func (x *ServiceCredential) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCredential.ProtoReflect.Descriptor instead.
func (*ServiceCredential) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_credential_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceCredential) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceCredential) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ServiceCredential) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceCredential) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ServiceCredential) GetStatus() CredentialStatus {
	if x != nil {
		return x.Status
	}
	return CredentialStatus_CREDENTIAL_STATUS_UNSPECIFIED
}

func (x *ServiceCredential) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *ServiceCredential) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *ServiceCredential) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateServiceCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceCredentialRequest) Reset() {
	*x = CreateServiceCredentialRequest{}
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceCredentialRequest) ProtoMessage() {}

func (x *CreateServiceCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceCredentialRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceCredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_credential_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServiceCredentialRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateServiceCredentialRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateServiceCredentialResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Credential *ServiceCredential     `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	// The secret, in clear text, returned exactly once. It is stored only as a
	// hash, so it cannot be recovered later — if it is lost, issue a new
	// credential and revoke this one.
	//
	// Present the credential to OpenPay as: Authorization: Bearer <key_id>.<secret>
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceCredentialResponse) Reset() {
	*x = CreateServiceCredentialResponse{}
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceCredentialResponse) ProtoMessage() {}

func (x *CreateServiceCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceCredentialResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceCredentialResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_credential_proto_rawDescGZIP(), []int{2}
}

func (x *CreateServiceCredentialResponse) GetCredential() *ServiceCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *CreateServiceCredentialResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ListServiceCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceCredentialsRequest) Reset() {
	*x = ListServiceCredentialsRequest{}
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceCredentialsRequest) ProtoMessage() {}

func (x *ListServiceCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ListServiceCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_credential_proto_rawDescGZIP(), []int{3}
}

func (x *ListServiceCredentialsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ListServiceCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*ServiceCredential   `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceCredentialsResponse) Reset() {
	*x = ListServiceCredentialsResponse{}
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceCredentialsResponse) ProtoMessage() {}

func (x *ListServiceCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ListServiceCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_credential_proto_rawDescGZIP(), []int{4}
}

func (x *ListServiceCredentialsResponse) GetCredentials() []*ServiceCredential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type RevokeServiceCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeServiceCredentialRequest) Reset() {
	*x = RevokeServiceCredentialRequest{}
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeServiceCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeServiceCredentialRequest) ProtoMessage() {}

func (x *RevokeServiceCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeServiceCredentialRequest.ProtoReflect.Descriptor instead.
func (*RevokeServiceCredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_credential_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeServiceCredentialRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RevokeServiceCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *ServiceCredential     `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeServiceCredentialResponse) Reset() {
	*x = RevokeServiceCredentialResponse{}
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeServiceCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeServiceCredentialResponse) ProtoMessage() {}

func (x *RevokeServiceCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_credential_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeServiceCredentialResponse.ProtoReflect.Descriptor instead.
func (*RevokeServiceCredentialResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_credential_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeServiceCredentialResponse) GetCredential() *ServiceCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

var File_proto_openpay_v1_credential_proto protoreflect.FileDescriptor

const file_proto_openpay_v1_credential_proto_rawDesc = "" +
	"\n" +
	"!proto/openpay/v1/credential.proto\x12\x02v1\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x02\n" +
	"\x11ServiceCredential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\tR\x05keyId\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.v1.CredentialStatusR\x06status\x12<\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"revoked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"g\n" +
	"\x1eCreateServiceCredentialRequest\x12&\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tproductId\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x04name\"p\n" +
	"\x1fCreateServiceCredentialResponse\x125\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x15.v1.ServiceCredentialR\n" +
	"credential\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"G\n" +
	"\x1dListServiceCredentialsRequest\x12&\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tproductId\"Y\n" +
	"\x1eListServiceCredentialsResponse\x127\n" +
	"\vcredentials\x18\x01 \x03(\v2\x15.v1.ServiceCredentialR\vcredentials\"9\n" +
	"\x1eRevokeServiceCredentialRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"X\n" +
	"\x1fRevokeServiceCredentialResponse\x125\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x15.v1.ServiceCredentialR\n" +
	"credential*r\n" +
	"\x10CredentialStatus\x12!\n" +
	"\x1dCREDENTIAL_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CREDENTIAL_STATUS_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19CREDENTIAL_STATUS_REVOKED\x10\x02B\x0eZ\f./openpay_v1b\x06proto3"

var (
	file_proto_openpay_v1_credential_proto_rawDescOnce sync.Once
	file_proto_openpay_v1_credential_proto_rawDescData []byte
)

func file_proto_openpay_v1_credential_proto_rawDescGZIP() []byte {
	file_proto_openpay_v1_credential_proto_rawDescOnce.Do(func() {
		file_proto_openpay_v1_credential_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_openpay_v1_credential_proto_rawDesc), len(file_proto_openpay_v1_credential_proto_rawDesc)))
	})
	return file_proto_openpay_v1_credential_proto_rawDescData
}

var file_proto_openpay_v1_credential_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_openpay_v1_credential_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_openpay_v1_credential_proto_goTypes = []any{
	(CredentialStatus)(0),                   // 0: v1.CredentialStatus
	(*ServiceCredential)(nil),               // 1: v1.ServiceCredential
	(*CreateServiceCredentialRequest)(nil),  // 2: v1.CreateServiceCredentialRequest
	(*CreateServiceCredentialResponse)(nil), // 3: v1.CreateServiceCredentialResponse
	(*ListServiceCredentialsRequest)(nil),   // 4: v1.ListServiceCredentialsRequest
	(*ListServiceCredentialsResponse)(nil),  // 5: v1.ListServiceCredentialsResponse
	(*RevokeServiceCredentialRequest)(nil),  // 6: v1.RevokeServiceCredentialRequest
	(*RevokeServiceCredentialResponse)(nil), // 7: v1.RevokeServiceCredentialResponse
	(*timestamppb.Timestamp)(nil),           // 8: google.protobuf.Timestamp
}
var file_proto_openpay_v1_credential_proto_depIdxs = []int32{
	0, // 0: v1.ServiceCredential.status:type_name -> v1.CredentialStatus
	8, // 1: v1.ServiceCredential.last_used_at:type_name -> google.protobuf.Timestamp
	8, // 2: v1.ServiceCredential.revoked_at:type_name -> google.protobuf.Timestamp
	8, // 3: v1.ServiceCredential.created_at:type_name -> google.protobuf.Timestamp
	1, // 4: v1.CreateServiceCredentialResponse.credential:type_name -> v1.ServiceCredential
	1, // 5: v1.ListServiceCredentialsResponse.credentials:type_name -> v1.ServiceCredential
	1, // 6: v1.RevokeServiceCredentialResponse.credential:type_name -> v1.ServiceCredential
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_openpay_v1_credential_proto_init() }
func file_proto_openpay_v1_credential_proto_init() {
	if File_proto_openpay_v1_credential_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_openpay_v1_credential_proto_rawDesc), len(file_proto_openpay_v1_credential_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_openpay_v1_credential_proto_goTypes,
		DependencyIndexes: file_proto_openpay_v1_credential_proto_depIdxs,
		EnumInfos:         file_proto_openpay_v1_credential_proto_enumTypes,
		MessageInfos:      file_proto_openpay_v1_credential_proto_msgTypes,
	}.Build()
	File_proto_openpay_v1_credential_proto = out.File
	file_proto_openpay_v1_credential_proto_goTypes = nil
	file_proto_openpay_v1_credential_proto_depIdxs = nil
}
