// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/openpay/v1/customer.proto

package openpay_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomerStatus int32

const (
	CustomerStatus_CUSTOMER_STATUS_UNSPECIFIED CustomerStatus = 0
	CustomerStatus_CUSTOMER_STATUS_ACTIVE      CustomerStatus = 1
	CustomerStatus_CUSTOMER_STATUS_BLOCKED     CustomerStatus = 2
	// A duplicate that now resolves to another record. Lookups follow it, so an
	// id stored before a merge keeps working.
	CustomerStatus_CUSTOMER_STATUS_MERGED CustomerStatus = 3
)

// Enum value maps for CustomerStatus.
var (
	CustomerStatus_name = map[int32]string{
		0: "CUSTOMER_STATUS_UNSPECIFIED",
		1: "CUSTOMER_STATUS_ACTIVE",
		2: "CUSTOMER_STATUS_BLOCKED",
		3: "CUSTOMER_STATUS_MERGED",
	}
	CustomerStatus_value = map[string]int32{
		"CUSTOMER_STATUS_UNSPECIFIED": 0,
		"CUSTOMER_STATUS_ACTIVE":      1,
		"CUSTOMER_STATUS_BLOCKED":     2,
		"CUSTOMER_STATUS_MERGED":      3,
	}
)

func (x CustomerStatus) Enum() *CustomerStatus {
	p := new(CustomerStatus)
	*p = x
	return p
}

func (x CustomerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_openpay_v1_customer_proto_enumTypes[0].Descriptor()
}

func (CustomerStatus) Type() protoreflect.EnumType {
	return &file_proto_openpay_v1_customer_proto_enumTypes[0]
}

func (x CustomerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomerStatus.Descriptor instead.
func (CustomerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_openpay_v1_customer_proto_rawDescGZIP(), []int{0}
}

// Customer is a person, not a per-product record: every product identifies
// people by the same OpenAuth user id, so one customer covers them everywhere.
type Customer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The OpenAuth user id.
	ExternalRef   string                 `protobuf:"bytes,2,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	Status        CustomerStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=v1.CustomerStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_proto_openpay_v1_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_customer_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *Customer) GetStatus() CustomerStatus {
	if x != nil {
		return x.Status
	}
	return CustomerStatus_CUSTOMER_STATUS_UNSPECIFIED
}

func (x *Customer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Customer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// UpsertCustomerRequest registers a person, or returns the existing record.
// Called by a product's backend the first time one of its users transacts.
type UpsertCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalRef   string                 `protobuf:"bytes,1,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertCustomerRequest) Reset() {
	*x = UpsertCustomerRequest{}
	mi := &file_proto_openpay_v1_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCustomerRequest) ProtoMessage() {}

func (x *UpsertCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCustomerRequest.ProtoReflect.Descriptor instead.
func (*UpsertCustomerRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_customer_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertCustomerRequest) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

type UpsertCustomerResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Customer *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	// False when the customer already existed, which lets a caller tell a first
	// registration from a repeat without a second lookup.
	Created       bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertCustomerResponse) Reset() {
	*x = UpsertCustomerResponse{}
	mi := &file_proto_openpay_v1_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCustomerResponse) ProtoMessage() {}

func (x *UpsertCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCustomerResponse.ProtoReflect.Descriptor instead.
func (*UpsertCustomerResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_customer_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *UpsertCustomerResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type GetCustomerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Either the OpenPay customer id or the OpenAuth external ref.
	//
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetCustomerRequest_Id
	//	*GetCustomerRequest_ExternalRef
	Identifier    isGetCustomerRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_proto_openpay_v1_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_customer_proto_rawDescGZIP(), []int{3}
}

func (x *GetCustomerRequest) GetIdentifier() isGetCustomerRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetCustomerRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetCustomerRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetCustomerRequest) GetExternalRef() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetCustomerRequest_ExternalRef); ok {
			return x.ExternalRef
		}
	}
	return ""
}

type isGetCustomerRequest_Identifier interface {
	isGetCustomerRequest_Identifier()
}

type GetCustomerRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetCustomerRequest_ExternalRef struct {
	ExternalRef string `protobuf:"bytes,2,opt,name=external_ref,json=externalRef,proto3,oneof"`
}

func (*GetCustomerRequest_Id) isGetCustomerRequest_Identifier() {}

func (*GetCustomerRequest_ExternalRef) isGetCustomerRequest_Identifier() {}

type GetCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerResponse) Reset() {
	*x = GetCustomerResponse{}
	mi := &file_proto_openpay_v1_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerResponse) ProtoMessage() {}

func (x *GetCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_customer_proto_rawDescGZIP(), []int{4}
}

func (x *GetCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

var File_proto_openpay_v1_customer_proto protoreflect.FileDescriptor

const file_proto_openpay_v1_customer_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/openpay/v1/customer.proto\x12\x02v1\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x01\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fexternal_ref\x18\x02 \x01(\tR\vexternalRef\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.v1.CustomerStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"F\n" +
	"\x15UpsertCustomerRequest\x12-\n" +
	"\fexternal_ref\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xc8\x01R\vexternalRef\"\\\n" +
	"\x16UpsertCustomerResponse\x12(\n" +
	"\bcustomer\x18\x01 \x01(\v2\f.v1.CustomerR\bcustomer\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"p\n" +
	"\x12GetCustomerRequest\x12\x19\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x00R\x02id\x12,\n" +
	"\fexternal_ref\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x00R\vexternalRefB\x11\n" +
	"\n" +
	"identifier\x12\x03\xf8B\x01\"?\n" +
	"\x13GetCustomerResponse\x12(\n" +
	"\bcustomer\x18\x01 \x01(\v2\f.v1.CustomerR\bcustomer*\x86\x01\n" +
	"\x0eCustomerStatus\x12\x1f\n" +
	"\x1bCUSTOMER_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CUSTOMER_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17CUSTOMER_STATUS_BLOCKED\x10\x02\x12\x1a\n" +
	"\x16CUSTOMER_STATUS_MERGED\x10\x03B\x0eZ\f./openpay_v1b\x06proto3"

var (
	file_proto_openpay_v1_customer_proto_rawDescOnce sync.Once
	file_proto_openpay_v1_customer_proto_rawDescData []byte
)

func file_proto_openpay_v1_customer_proto_rawDescGZIP() []byte {
	file_proto_openpay_v1_customer_proto_rawDescOnce.Do(func() {
		file_proto_openpay_v1_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_openpay_v1_customer_proto_rawDesc), len(file_proto_openpay_v1_customer_proto_rawDesc)))
	})
	return file_proto_openpay_v1_customer_proto_rawDescData
}

var file_proto_openpay_v1_customer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_openpay_v1_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_openpay_v1_customer_proto_goTypes = []any{
	(CustomerStatus)(0),            // 0: v1.CustomerStatus
	(*Customer)(nil),               // 1: v1.Customer
	(*UpsertCustomerRequest)(nil),  // 2: v1.UpsertCustomerRequest
	(*UpsertCustomerResponse)(nil), // 3: v1.UpsertCustomerResponse
	(*GetCustomerRequest)(nil),     // 4: v1.GetCustomerRequest
	(*GetCustomerResponse)(nil),    // 5: v1.GetCustomerResponse
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_proto_openpay_v1_customer_proto_depIdxs = []int32{
	0, // 0: v1.Customer.status:type_name -> v1.CustomerStatus
	6, // 1: v1.Customer.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: v1.Customer.updated_at:type_name -> google.protobuf.Timestamp
	1, // 3: v1.UpsertCustomerResponse.customer:type_name -> v1.Customer
	1, // 4: v1.GetCustomerResponse.customer:type_name -> v1.Customer
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_openpay_v1_customer_proto_init() }
func file_proto_openpay_v1_customer_proto_init() {
	if File_proto_openpay_v1_customer_proto != nil {
		return
	}
	file_proto_openpay_v1_customer_proto_msgTypes[3].OneofWrappers = []any{
		(*GetCustomerRequest_Id)(nil),
		(*GetCustomerRequest_ExternalRef)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_openpay_v1_customer_proto_rawDesc), len(file_proto_openpay_v1_customer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_openpay_v1_customer_proto_goTypes,
		DependencyIndexes: file_proto_openpay_v1_customer_proto_depIdxs,
		EnumInfos:         file_proto_openpay_v1_customer_proto_enumTypes,
		MessageInfos:      file_proto_openpay_v1_customer_proto_msgTypes,
	}.Build()
	File_proto_openpay_v1_customer_proto = out.File
	file_proto_openpay_v1_customer_proto_goTypes = nil
	file_proto_openpay_v1_customer_proto_depIdxs = nil
}
