// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/openpay/v1/ledger.proto

package openpay_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LedgerBalance with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LedgerBalance) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LedgerBalance with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LedgerBalanceMultiError, or
// nil if none found.
func (m *LedgerBalance) ValidateAll() error {
	return m.validate(true)
}

func (m *LedgerBalance) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Balance

	// no validation rules for Held

	// no validation rules for Available

	if len(errors) > 0 {
		return LedgerBalanceMultiError(errors)
	}

	return nil
}

// LedgerBalanceMultiError is an error wrapping multiple validation errors
// returned by LedgerBalance.ValidateAll() if the designated constraints
// aren't met.
type LedgerBalanceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LedgerBalanceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LedgerBalanceMultiError) AllErrors() []error { return m }

// LedgerBalanceValidationError is the validation error returned by
// LedgerBalance.Validate if the designated constraints aren't met.
type LedgerBalanceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LedgerBalanceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LedgerBalanceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LedgerBalanceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LedgerBalanceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LedgerBalanceValidationError) ErrorName() string { return "LedgerBalanceValidationError" }

// Error satisfies the builtin error interface
func (e LedgerBalanceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLedgerBalance.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LedgerBalanceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LedgerBalanceValidationError{}

// Validate checks the field values on LedgerAccount with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LedgerAccount) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LedgerAccount with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LedgerAccountMultiError, or
// nil if none found.
func (m *LedgerAccount) ValidateAll() error {
	return m.validate(true)
}

func (m *LedgerAccount) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Code

	// no validation rules for ProductId

	// no validation rules for Type

	// no validation rules for Currency

	// no validation rules for OwnerKind

	// no validation rules for OwnerId

	// no validation rules for AllowNegative

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetBalance()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LedgerAccountValidationError{
					field:  "Balance",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LedgerAccountValidationError{
					field:  "Balance",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBalance()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LedgerAccountValidationError{
				field:  "Balance",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LedgerAccountValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LedgerAccountValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LedgerAccountValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LedgerAccountMultiError(errors)
	}

	return nil
}

// LedgerAccountMultiError is an error wrapping multiple validation errors
// returned by LedgerAccount.ValidateAll() if the designated constraints
// aren't met.
type LedgerAccountMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LedgerAccountMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LedgerAccountMultiError) AllErrors() []error { return m }

// LedgerAccountValidationError is the validation error returned by
// LedgerAccount.Validate if the designated constraints aren't met.
type LedgerAccountValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LedgerAccountValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LedgerAccountValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LedgerAccountValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LedgerAccountValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LedgerAccountValidationError) ErrorName() string { return "LedgerAccountValidationError" }

// Error satisfies the builtin error interface
func (e LedgerAccountValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLedgerAccount.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LedgerAccountValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LedgerAccountValidationError{}

// Validate checks the field values on GetLedgerAccountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetLedgerAccountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLedgerAccountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetLedgerAccountRequestMultiError, or nil if none found.
func (m *GetLedgerAccountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLedgerAccountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetId()); l < 1 || l > 300 {
		err := GetLedgerAccountRequestValidationError{
			field:  "Id",
			reason: "value length must be between 1 and 300 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetLedgerAccountRequestMultiError(errors)
	}

	return nil
}

// GetLedgerAccountRequestMultiError is an error wrapping multiple validation
// errors returned by GetLedgerAccountRequest.ValidateAll() if the designated
// constraints aren't met.
type GetLedgerAccountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLedgerAccountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLedgerAccountRequestMultiError) AllErrors() []error { return m }

// GetLedgerAccountRequestValidationError is the validation error returned by
// GetLedgerAccountRequest.Validate if the designated constraints aren't met.
type GetLedgerAccountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLedgerAccountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLedgerAccountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLedgerAccountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLedgerAccountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLedgerAccountRequestValidationError) ErrorName() string {
	return "GetLedgerAccountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetLedgerAccountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLedgerAccountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLedgerAccountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLedgerAccountRequestValidationError{}

// Validate checks the field values on GetLedgerAccountResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetLedgerAccountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLedgerAccountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetLedgerAccountResponseMultiError, or nil if none found.
func (m *GetLedgerAccountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLedgerAccountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAccount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetLedgerAccountResponseValidationError{
					field:  "Account",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetLedgerAccountResponseValidationError{
					field:  "Account",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAccount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetLedgerAccountResponseValidationError{
				field:  "Account",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetLedgerAccountResponseMultiError(errors)
	}

	return nil
}

// GetLedgerAccountResponseMultiError is an error wrapping multiple validation
// errors returned by GetLedgerAccountResponse.ValidateAll() if the designated
// constraints aren't met.
type GetLedgerAccountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLedgerAccountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLedgerAccountResponseMultiError) AllErrors() []error { return m }

// GetLedgerAccountResponseValidationError is the validation error returned by
// GetLedgerAccountResponse.Validate if the designated constraints aren't met.
type GetLedgerAccountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLedgerAccountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLedgerAccountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLedgerAccountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLedgerAccountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLedgerAccountResponseValidationError) ErrorName() string {
	return "GetLedgerAccountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetLedgerAccountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLedgerAccountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLedgerAccountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLedgerAccountResponseValidationError{}

// Validate checks the field values on ListLedgerAccountsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListLedgerAccountsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListLedgerAccountsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListLedgerAccountsRequestMultiError, or nil if none found.
func (m *ListLedgerAccountsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListLedgerAccountsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetLimit(); val < 0 || val > 100 {
		err := ListLedgerAccountsRequestValidationError{
			field:  "Limit",
			reason: "value must be inside range [0, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOffset() < 0 {
		err := ListLedgerAccountsRequestValidationError{
			field:  "Offset",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ProductId

	// no validation rules for PlatformOnly

	if _, ok := LedgerAccountType_name[int32(m.GetType())]; !ok {
		err := ListLedgerAccountsRequestValidationError{
			field:  "Type",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCodePrefix()) > 300 {
		err := ListLedgerAccountsRequestValidationError{
			field:  "CodePrefix",
			reason: "value length must be at most 300 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListLedgerAccountsRequestMultiError(errors)
	}

	return nil
}

// ListLedgerAccountsRequestMultiError is an error wrapping multiple validation
// errors returned by ListLedgerAccountsRequest.ValidateAll() if the
// designated constraints aren't met.
type ListLedgerAccountsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListLedgerAccountsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListLedgerAccountsRequestMultiError) AllErrors() []error { return m }

// ListLedgerAccountsRequestValidationError is the validation error returned by
// ListLedgerAccountsRequest.Validate if the designated constraints aren't met.
type ListLedgerAccountsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListLedgerAccountsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListLedgerAccountsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListLedgerAccountsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListLedgerAccountsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListLedgerAccountsRequestValidationError) ErrorName() string {
	return "ListLedgerAccountsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListLedgerAccountsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListLedgerAccountsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListLedgerAccountsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListLedgerAccountsRequestValidationError{}

// Validate checks the field values on ListLedgerAccountsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListLedgerAccountsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListLedgerAccountsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListLedgerAccountsResponseMultiError, or nil if none found.
func (m *ListLedgerAccountsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListLedgerAccountsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetAccounts() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListLedgerAccountsResponseValidationError{
						field:  fmt.Sprintf("Accounts[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListLedgerAccountsResponseValidationError{
						field:  fmt.Sprintf("Accounts[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListLedgerAccountsResponseValidationError{
					field:  fmt.Sprintf("Accounts[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListLedgerAccountsResponseMultiError(errors)
	}

	return nil
}

// ListLedgerAccountsResponseMultiError is an error wrapping multiple
// validation errors returned by ListLedgerAccountsResponse.ValidateAll() if
// the designated constraints aren't met.
type ListLedgerAccountsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListLedgerAccountsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListLedgerAccountsResponseMultiError) AllErrors() []error { return m }

// ListLedgerAccountsResponseValidationError is the validation error returned
// by ListLedgerAccountsResponse.Validate if the designated constraints aren't met.
type ListLedgerAccountsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListLedgerAccountsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListLedgerAccountsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListLedgerAccountsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListLedgerAccountsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListLedgerAccountsResponseValidationError) ErrorName() string {
	return "ListLedgerAccountsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListLedgerAccountsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListLedgerAccountsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListLedgerAccountsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListLedgerAccountsResponseValidationError{}

// Validate checks the field values on StatementEntry with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StatementEntry) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StatementEntry with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StatementEntryMultiError,
// or nil if none found.
func (m *StatementEntry) ValidateAll() error {
	return m.validate(true)
}

func (m *StatementEntry) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for JournalId

	// no validation rules for JournalExternalId

	// no validation rules for JournalKind

	// no validation rules for Memo

	// no validation rules for Direction

	// no validation rules for Amount

	// no validation rules for Change

	// no validation rules for BalanceAfter

	if all {
		switch v := interface{}(m.GetPostedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StatementEntryValidationError{
					field:  "PostedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StatementEntryValidationError{
					field:  "PostedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPostedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StatementEntryValidationError{
				field:  "PostedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return StatementEntryMultiError(errors)
	}

	return nil
}

// StatementEntryMultiError is an error wrapping multiple validation errors
// returned by StatementEntry.ValidateAll() if the designated constraints
// aren't met.
type StatementEntryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StatementEntryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StatementEntryMultiError) AllErrors() []error { return m }

// StatementEntryValidationError is the validation error returned by
// StatementEntry.Validate if the designated constraints aren't met.
type StatementEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StatementEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StatementEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StatementEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StatementEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StatementEntryValidationError) ErrorName() string { return "StatementEntryValidationError" }

// Error satisfies the builtin error interface
func (e StatementEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStatementEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StatementEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StatementEntryValidationError{}

// Validate checks the field values on GetAccountStatementRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAccountStatementRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAccountStatementRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAccountStatementRequestMultiError, or nil if none found.
func (m *GetAccountStatementRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAccountStatementRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetAccountId()); l < 1 || l > 300 {
		err := GetAccountStatementRequestValidationError{
			field:  "AccountId",
			reason: "value length must be between 1 and 300 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetLimit(); val < 0 || val > 100 {
		err := GetAccountStatementRequestValidationError{
			field:  "Limit",
			reason: "value must be inside range [0, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCursor()) > 50 {
		err := GetAccountStatementRequestValidationError{
			field:  "Cursor",
			reason: "value length must be at most 50 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetAccountStatementRequestMultiError(errors)
	}

	return nil
}

// GetAccountStatementRequestMultiError is an error wrapping multiple
// validation errors returned by GetAccountStatementRequest.ValidateAll() if
// the designated constraints aren't met.
type GetAccountStatementRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAccountStatementRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAccountStatementRequestMultiError) AllErrors() []error { return m }

// GetAccountStatementRequestValidationError is the validation error returned
// by GetAccountStatementRequest.Validate if the designated constraints aren't met.
type GetAccountStatementRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAccountStatementRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAccountStatementRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAccountStatementRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAccountStatementRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAccountStatementRequestValidationError) ErrorName() string {
	return "GetAccountStatementRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAccountStatementRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAccountStatementRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAccountStatementRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAccountStatementRequestValidationError{}

// Validate checks the field values on GetAccountStatementResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAccountStatementResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAccountStatementResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAccountStatementResponseMultiError, or nil if none found.
func (m *GetAccountStatementResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAccountStatementResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAccount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetAccountStatementResponseValidationError{
					field:  "Account",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetAccountStatementResponseValidationError{
					field:  "Account",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAccount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetAccountStatementResponseValidationError{
				field:  "Account",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetEntries() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetAccountStatementResponseValidationError{
						field:  fmt.Sprintf("Entries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetAccountStatementResponseValidationError{
						field:  fmt.Sprintf("Entries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAccountStatementResponseValidationError{
					field:  fmt.Sprintf("Entries[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextCursor

	if len(errors) > 0 {
		return GetAccountStatementResponseMultiError(errors)
	}

	return nil
}

// GetAccountStatementResponseMultiError is an error wrapping multiple
// validation errors returned by GetAccountStatementResponse.ValidateAll() if
// the designated constraints aren't met.
type GetAccountStatementResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAccountStatementResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAccountStatementResponseMultiError) AllErrors() []error { return m }

// GetAccountStatementResponseValidationError is the validation error returned
// by GetAccountStatementResponse.Validate if the designated constraints
// aren't met.
type GetAccountStatementResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAccountStatementResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAccountStatementResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAccountStatementResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAccountStatementResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAccountStatementResponseValidationError) ErrorName() string {
	return "GetAccountStatementResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAccountStatementResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAccountStatementResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAccountStatementResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAccountStatementResponseValidationError{}

// Validate checks the field values on JournalPosting with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *JournalPosting) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JournalPosting with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in JournalPostingMultiError,
// or nil if none found.
func (m *JournalPosting) ValidateAll() error {
	return m.validate(true)
}

func (m *JournalPosting) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccountId

	// no validation rules for AccountCode

	// no validation rules for Direction

	// no validation rules for Amount

	// no validation rules for Currency

	if len(errors) > 0 {
		return JournalPostingMultiError(errors)
	}

	return nil
}

// JournalPostingMultiError is an error wrapping multiple validation errors
// returned by JournalPosting.ValidateAll() if the designated constraints
// aren't met.
type JournalPostingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JournalPostingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JournalPostingMultiError) AllErrors() []error { return m }

// JournalPostingValidationError is the validation error returned by
// JournalPosting.Validate if the designated constraints aren't met.
type JournalPostingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JournalPostingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JournalPostingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JournalPostingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JournalPostingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JournalPostingValidationError) ErrorName() string { return "JournalPostingValidationError" }

// Error satisfies the builtin error interface
func (e JournalPostingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJournalPosting.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JournalPostingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JournalPostingValidationError{}

// Validate checks the field values on Journal with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Journal) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Journal with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in JournalMultiError, or nil if none found.
func (m *Journal) ValidateAll() error {
	return m.validate(true)
}

func (m *Journal) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ExternalId

	// no validation rules for Kind

	// no validation rules for ProductId

	// no validation rules for SourceKind

	// no validation rules for SourceId

	// no validation rules for ReversesJournalId

	// no validation rules for Memo

	for idx, item := range m.GetPostings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, JournalValidationError{
						field:  fmt.Sprintf("Postings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, JournalValidationError{
						field:  fmt.Sprintf("Postings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return JournalValidationError{
					field:  fmt.Sprintf("Postings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPostedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, JournalValidationError{
					field:  "PostedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, JournalValidationError{
					field:  "PostedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPostedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return JournalValidationError{
				field:  "PostedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return JournalMultiError(errors)
	}

	return nil
}

// JournalMultiError is an error wrapping multiple validation errors returned
// by Journal.ValidateAll() if the designated constraints aren't met.
type JournalMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JournalMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JournalMultiError) AllErrors() []error { return m }

// JournalValidationError is the validation error returned by Journal.Validate
// if the designated constraints aren't met.
type JournalValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JournalValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JournalValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JournalValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JournalValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JournalValidationError) ErrorName() string { return "JournalValidationError" }

// Error satisfies the builtin error interface
func (e JournalValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJournal.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JournalValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JournalValidationError{}

// Validate checks the field values on GetJournalRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetJournalRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetJournalRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetJournalRequestMultiError, or nil if none found.
func (m *GetJournalRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetJournalRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetId()); l < 1 || l > 300 {
		err := GetJournalRequestValidationError{
			field:  "Id",
			reason: "value length must be between 1 and 300 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetJournalRequestMultiError(errors)
	}

	return nil
}

// GetJournalRequestMultiError is an error wrapping multiple validation errors
// returned by GetJournalRequest.ValidateAll() if the designated constraints
// aren't met.
type GetJournalRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetJournalRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetJournalRequestMultiError) AllErrors() []error { return m }

// GetJournalRequestValidationError is the validation error returned by
// GetJournalRequest.Validate if the designated constraints aren't met.
type GetJournalRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetJournalRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetJournalRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetJournalRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetJournalRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetJournalRequestValidationError) ErrorName() string {
	return "GetJournalRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetJournalRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetJournalRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetJournalRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetJournalRequestValidationError{}

// Validate checks the field values on GetJournalResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetJournalResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetJournalResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetJournalResponseMultiError, or nil if none found.
func (m *GetJournalResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetJournalResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetJournal()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetJournalResponseValidationError{
					field:  "Journal",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetJournalResponseValidationError{
					field:  "Journal",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetJournal()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetJournalResponseValidationError{
				field:  "Journal",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetJournalResponseMultiError(errors)
	}

	return nil
}

// GetJournalResponseMultiError is an error wrapping multiple validation errors
// returned by GetJournalResponse.ValidateAll() if the designated constraints
// aren't met.
type GetJournalResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetJournalResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetJournalResponseMultiError) AllErrors() []error { return m }

// GetJournalResponseValidationError is the validation error returned by
// GetJournalResponse.Validate if the designated constraints aren't met.
type GetJournalResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetJournalResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetJournalResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetJournalResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetJournalResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetJournalResponseValidationError) ErrorName() string {
	return "GetJournalResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetJournalResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetJournalResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetJournalResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetJournalResponseValidationError{}

// Validate checks the field values on TrialBalanceLine with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TrialBalanceLine) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TrialBalanceLine with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TrialBalanceLineMultiError, or nil if none found.
func (m *TrialBalanceLine) ValidateAll() error {
	return m.validate(true)
}

func (m *TrialBalanceLine) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccountId

	// no validation rules for AccountCode

	// no validation rules for Type

	// no validation rules for ProductId

	// no validation rules for Currency

	// no validation rules for Debits

	// no validation rules for Credits

	// no validation rules for RawBalance

	// no validation rules for Balance

	if len(errors) > 0 {
		return TrialBalanceLineMultiError(errors)
	}

	return nil
}

// TrialBalanceLineMultiError is an error wrapping multiple validation errors
// returned by TrialBalanceLine.ValidateAll() if the designated constraints
// aren't met.
type TrialBalanceLineMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrialBalanceLineMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrialBalanceLineMultiError) AllErrors() []error { return m }

// TrialBalanceLineValidationError is the validation error returned by
// TrialBalanceLine.Validate if the designated constraints aren't met.
type TrialBalanceLineValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrialBalanceLineValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrialBalanceLineValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrialBalanceLineValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrialBalanceLineValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrialBalanceLineValidationError) ErrorName() string { return "TrialBalanceLineValidationError" }

// Error satisfies the builtin error interface
func (e TrialBalanceLineValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrialBalanceLine.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrialBalanceLineValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrialBalanceLineValidationError{}

// Validate checks the field values on TrialBalanceTotal with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TrialBalanceTotal) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TrialBalanceTotal with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TrialBalanceTotalMultiError, or nil if none found.
func (m *TrialBalanceTotal) ValidateAll() error {
	return m.validate(true)
}

func (m *TrialBalanceTotal) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Currency

	// no validation rules for Debits

	// no validation rules for Credits

	// no validation rules for Difference

	if len(errors) > 0 {
		return TrialBalanceTotalMultiError(errors)
	}

	return nil
}

// TrialBalanceTotalMultiError is an error wrapping multiple validation errors
// returned by TrialBalanceTotal.ValidateAll() if the designated constraints
// aren't met.
type TrialBalanceTotalMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrialBalanceTotalMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrialBalanceTotalMultiError) AllErrors() []error { return m }

// TrialBalanceTotalValidationError is the validation error returned by
// TrialBalanceTotal.Validate if the designated constraints aren't met.
type TrialBalanceTotalValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrialBalanceTotalValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrialBalanceTotalValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrialBalanceTotalValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrialBalanceTotalValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrialBalanceTotalValidationError) ErrorName() string {
	return "TrialBalanceTotalValidationError"
}

// Error satisfies the builtin error interface
func (e TrialBalanceTotalValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrialBalanceTotal.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrialBalanceTotalValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrialBalanceTotalValidationError{}

// Validate checks the field values on GetTrialBalanceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTrialBalanceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTrialBalanceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTrialBalanceRequestMultiError, or nil if none found.
func (m *GetTrialBalanceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTrialBalanceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProductId

	if all {
		switch v := interface{}(m.GetAsOf()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetTrialBalanceRequestValidationError{
					field:  "AsOf",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetTrialBalanceRequestValidationError{
					field:  "AsOf",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAsOf()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetTrialBalanceRequestValidationError{
				field:  "AsOf",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for IncludeEmpty

	if len(errors) > 0 {
		return GetTrialBalanceRequestMultiError(errors)
	}

	return nil
}

// GetTrialBalanceRequestMultiError is an error wrapping multiple validation
// errors returned by GetTrialBalanceRequest.ValidateAll() if the designated
// constraints aren't met.
type GetTrialBalanceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTrialBalanceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTrialBalanceRequestMultiError) AllErrors() []error { return m }

// GetTrialBalanceRequestValidationError is the validation error returned by
// GetTrialBalanceRequest.Validate if the designated constraints aren't met.
type GetTrialBalanceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTrialBalanceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTrialBalanceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTrialBalanceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTrialBalanceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTrialBalanceRequestValidationError) ErrorName() string {
	return "GetTrialBalanceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTrialBalanceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTrialBalanceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTrialBalanceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTrialBalanceRequestValidationError{}

// Validate checks the field values on GetTrialBalanceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTrialBalanceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTrialBalanceResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTrialBalanceResponseMultiError, or nil if none found.
func (m *GetTrialBalanceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTrialBalanceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetLines() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetTrialBalanceResponseValidationError{
						field:  fmt.Sprintf("Lines[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetTrialBalanceResponseValidationError{
						field:  fmt.Sprintf("Lines[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetTrialBalanceResponseValidationError{
					field:  fmt.Sprintf("Lines[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetTotals() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetTrialBalanceResponseValidationError{
						field:  fmt.Sprintf("Totals[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetTrialBalanceResponseValidationError{
						field:  fmt.Sprintf("Totals[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetTrialBalanceResponseValidationError{
					field:  fmt.Sprintf("Totals[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetAsOf()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetTrialBalanceResponseValidationError{
					field:  "AsOf",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetTrialBalanceResponseValidationError{
					field:  "AsOf",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAsOf()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetTrialBalanceResponseValidationError{
				field:  "AsOf",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetTrialBalanceResponseMultiError(errors)
	}

	return nil
}

// GetTrialBalanceResponseMultiError is an error wrapping multiple validation
// errors returned by GetTrialBalanceResponse.ValidateAll() if the designated
// constraints aren't met.
type GetTrialBalanceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTrialBalanceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTrialBalanceResponseMultiError) AllErrors() []error { return m }

// GetTrialBalanceResponseValidationError is the validation error returned by
// GetTrialBalanceResponse.Validate if the designated constraints aren't met.
type GetTrialBalanceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTrialBalanceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTrialBalanceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTrialBalanceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTrialBalanceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTrialBalanceResponseValidationError) ErrorName() string {
	return "GetTrialBalanceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetTrialBalanceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTrialBalanceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTrialBalanceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTrialBalanceResponseValidationError{}

// Validate checks the field values on LedgerCheckFinding with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *LedgerCheckFinding) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LedgerCheckFinding with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LedgerCheckFindingMultiError, or nil if none found.
func (m *LedgerCheckFinding) ValidateAll() error {
	return m.validate(true)
}

func (m *LedgerCheckFinding) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Invariant

	// no validation rules for Subject

	// no validation rules for Expected

	// no validation rules for Actual

	// no validation rules for Detail

	if len(errors) > 0 {
		return LedgerCheckFindingMultiError(errors)
	}

	return nil
}

// LedgerCheckFindingMultiError is an error wrapping multiple validation errors
// returned by LedgerCheckFinding.ValidateAll() if the designated constraints
// aren't met.
type LedgerCheckFindingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LedgerCheckFindingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LedgerCheckFindingMultiError) AllErrors() []error { return m }

// LedgerCheckFindingValidationError is the validation error returned by
// LedgerCheckFinding.Validate if the designated constraints aren't met.
type LedgerCheckFindingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LedgerCheckFindingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LedgerCheckFindingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LedgerCheckFindingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LedgerCheckFindingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LedgerCheckFindingValidationError) ErrorName() string {
	return "LedgerCheckFindingValidationError"
}

// Error satisfies the builtin error interface
func (e LedgerCheckFindingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLedgerCheckFinding.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LedgerCheckFindingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LedgerCheckFindingValidationError{}

// Validate checks the field values on LedgerCheckRun with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LedgerCheckRun) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LedgerCheckRun with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LedgerCheckRunMultiError,
// or nil if none found.
func (m *LedgerCheckRun) ValidateAll() error {
	return m.validate(true)
}

func (m *LedgerCheckRun) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Status

	// no validation rules for Trigger

	// no validation rules for TriggeredBy

	for idx, item := range m.GetFindings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, LedgerCheckRunValidationError{
						field:  fmt.Sprintf("Findings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, LedgerCheckRunValidationError{
						field:  fmt.Sprintf("Findings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return LedgerCheckRunValidationError{
					field:  fmt.Sprintf("Findings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Truncated

	// no validation rules for Error

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LedgerCheckRunValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LedgerCheckRunValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LedgerCheckRunValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetFinishedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LedgerCheckRunValidationError{
					field:  "FinishedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LedgerCheckRunValidationError{
					field:  "FinishedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFinishedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LedgerCheckRunValidationError{
				field:  "FinishedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LedgerCheckRunMultiError(errors)
	}

	return nil
}

// LedgerCheckRunMultiError is an error wrapping multiple validation errors
// returned by LedgerCheckRun.ValidateAll() if the designated constraints
// aren't met.
type LedgerCheckRunMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LedgerCheckRunMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LedgerCheckRunMultiError) AllErrors() []error { return m }

// LedgerCheckRunValidationError is the validation error returned by
// LedgerCheckRun.Validate if the designated constraints aren't met.
type LedgerCheckRunValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LedgerCheckRunValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LedgerCheckRunValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LedgerCheckRunValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LedgerCheckRunValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LedgerCheckRunValidationError) ErrorName() string { return "LedgerCheckRunValidationError" }

// Error satisfies the builtin error interface
func (e LedgerCheckRunValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLedgerCheckRun.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LedgerCheckRunValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LedgerCheckRunValidationError{}

// Validate checks the field values on RunLedgerCheckRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RunLedgerCheckRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RunLedgerCheckRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RunLedgerCheckRequestMultiError, or nil if none found.
func (m *RunLedgerCheckRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RunLedgerCheckRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RunLedgerCheckRequestMultiError(errors)
	}

	return nil
}

// RunLedgerCheckRequestMultiError is an error wrapping multiple validation
// errors returned by RunLedgerCheckRequest.ValidateAll() if the designated
// constraints aren't met.
type RunLedgerCheckRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RunLedgerCheckRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RunLedgerCheckRequestMultiError) AllErrors() []error { return m }

// RunLedgerCheckRequestValidationError is the validation error returned by
// RunLedgerCheckRequest.Validate if the designated constraints aren't met.
type RunLedgerCheckRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RunLedgerCheckRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RunLedgerCheckRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RunLedgerCheckRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RunLedgerCheckRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RunLedgerCheckRequestValidationError) ErrorName() string {
	return "RunLedgerCheckRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RunLedgerCheckRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRunLedgerCheckRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RunLedgerCheckRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RunLedgerCheckRequestValidationError{}

// Validate checks the field values on RunLedgerCheckResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RunLedgerCheckResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RunLedgerCheckResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RunLedgerCheckResponseMultiError, or nil if none found.
func (m *RunLedgerCheckResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RunLedgerCheckResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRun()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RunLedgerCheckResponseValidationError{
					field:  "Run",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RunLedgerCheckResponseValidationError{
					field:  "Run",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRun()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RunLedgerCheckResponseValidationError{
				field:  "Run",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RunLedgerCheckResponseMultiError(errors)
	}

	return nil
}

// RunLedgerCheckResponseMultiError is an error wrapping multiple validation
// errors returned by RunLedgerCheckResponse.ValidateAll() if the designated
// constraints aren't met.
type RunLedgerCheckResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RunLedgerCheckResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RunLedgerCheckResponseMultiError) AllErrors() []error { return m }

// RunLedgerCheckResponseValidationError is the validation error returned by
// RunLedgerCheckResponse.Validate if the designated constraints aren't met.
type RunLedgerCheckResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RunLedgerCheckResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RunLedgerCheckResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RunLedgerCheckResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RunLedgerCheckResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RunLedgerCheckResponseValidationError) ErrorName() string {
	return "RunLedgerCheckResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RunLedgerCheckResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRunLedgerCheckResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RunLedgerCheckResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RunLedgerCheckResponseValidationError{}

// Validate checks the field values on ListLedgerCheckRunsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListLedgerCheckRunsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListLedgerCheckRunsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListLedgerCheckRunsRequestMultiError, or nil if none found.
func (m *ListLedgerCheckRunsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListLedgerCheckRunsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetLimit(); val < 0 || val > 100 {
		err := ListLedgerCheckRunsRequestValidationError{
			field:  "Limit",
			reason: "value must be inside range [0, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListLedgerCheckRunsRequestMultiError(errors)
	}

	return nil
}

// ListLedgerCheckRunsRequestMultiError is an error wrapping multiple
// validation errors returned by ListLedgerCheckRunsRequest.ValidateAll() if
// the designated constraints aren't met.
type ListLedgerCheckRunsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListLedgerCheckRunsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListLedgerCheckRunsRequestMultiError) AllErrors() []error { return m }

// ListLedgerCheckRunsRequestValidationError is the validation error returned
// by ListLedgerCheckRunsRequest.Validate if the designated constraints aren't met.
type ListLedgerCheckRunsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListLedgerCheckRunsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListLedgerCheckRunsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListLedgerCheckRunsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListLedgerCheckRunsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListLedgerCheckRunsRequestValidationError) ErrorName() string {
	return "ListLedgerCheckRunsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListLedgerCheckRunsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListLedgerCheckRunsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListLedgerCheckRunsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListLedgerCheckRunsRequestValidationError{}

// Validate checks the field values on ListLedgerCheckRunsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListLedgerCheckRunsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListLedgerCheckRunsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListLedgerCheckRunsResponseMultiError, or nil if none found.
func (m *ListLedgerCheckRunsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListLedgerCheckRunsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRuns() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListLedgerCheckRunsResponseValidationError{
						field:  fmt.Sprintf("Runs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListLedgerCheckRunsResponseValidationError{
						field:  fmt.Sprintf("Runs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListLedgerCheckRunsResponseValidationError{
					field:  fmt.Sprintf("Runs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListLedgerCheckRunsResponseMultiError(errors)
	}

	return nil
}

// ListLedgerCheckRunsResponseMultiError is an error wrapping multiple
// validation errors returned by ListLedgerCheckRunsResponse.ValidateAll() if
// the designated constraints aren't met.
type ListLedgerCheckRunsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListLedgerCheckRunsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListLedgerCheckRunsResponseMultiError) AllErrors() []error { return m }

// ListLedgerCheckRunsResponseValidationError is the validation error returned
// by ListLedgerCheckRunsResponse.Validate if the designated constraints
// aren't met.
type ListLedgerCheckRunsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListLedgerCheckRunsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListLedgerCheckRunsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListLedgerCheckRunsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListLedgerCheckRunsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListLedgerCheckRunsResponseValidationError) ErrorName() string {
	return "ListLedgerCheckRunsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListLedgerCheckRunsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListLedgerCheckRunsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListLedgerCheckRunsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListLedgerCheckRunsResponseValidationError{}
