// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/openpay/v1/ledger.proto

package openpay_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LedgerAccountType int32

const (
	LedgerAccountType_LEDGER_ACCOUNT_TYPE_UNSPECIFIED LedgerAccountType = 0
	LedgerAccountType_LEDGER_ACCOUNT_TYPE_ASSET       LedgerAccountType = 1
	LedgerAccountType_LEDGER_ACCOUNT_TYPE_LIABILITY   LedgerAccountType = 2
	LedgerAccountType_LEDGER_ACCOUNT_TYPE_EQUITY      LedgerAccountType = 3
	LedgerAccountType_LEDGER_ACCOUNT_TYPE_INCOME      LedgerAccountType = 4
	LedgerAccountType_LEDGER_ACCOUNT_TYPE_EXPENSE     LedgerAccountType = 5
)

// Enum value maps for LedgerAccountType.
var (
	LedgerAccountType_name = map[int32]string{
		0: "LEDGER_ACCOUNT_TYPE_UNSPECIFIED",
		1: "LEDGER_ACCOUNT_TYPE_ASSET",
		2: "LEDGER_ACCOUNT_TYPE_LIABILITY",
		3: "LEDGER_ACCOUNT_TYPE_EQUITY",
		4: "LEDGER_ACCOUNT_TYPE_INCOME",
		5: "LEDGER_ACCOUNT_TYPE_EXPENSE",
	}
	LedgerAccountType_value = map[string]int32{
		"LEDGER_ACCOUNT_TYPE_UNSPECIFIED": 0,
		"LEDGER_ACCOUNT_TYPE_ASSET":       1,
		"LEDGER_ACCOUNT_TYPE_LIABILITY":   2,
		"LEDGER_ACCOUNT_TYPE_EQUITY":      3,
		"LEDGER_ACCOUNT_TYPE_INCOME":      4,
		"LEDGER_ACCOUNT_TYPE_EXPENSE":     5,
	}
)

func (x LedgerAccountType) Enum() *LedgerAccountType {
	p := new(LedgerAccountType)
	*p = x
	return p
}

func (x LedgerAccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerAccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_openpay_v1_ledger_proto_enumTypes[0].Descriptor()
}

func (LedgerAccountType) Type() protoreflect.EnumType {
	return &file_proto_openpay_v1_ledger_proto_enumTypes[0]
}

func (x LedgerAccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerAccountType.Descriptor instead.
func (LedgerAccountType) EnumDescriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{0}
}

type PostingDirection int32

const (
	PostingDirection_POSTING_DIRECTION_UNSPECIFIED PostingDirection = 0
	PostingDirection_POSTING_DIRECTION_DEBIT       PostingDirection = 1
	PostingDirection_POSTING_DIRECTION_CREDIT      PostingDirection = 2
)

// Enum value maps for PostingDirection.
var (
	PostingDirection_name = map[int32]string{
		0: "POSTING_DIRECTION_UNSPECIFIED",
		1: "POSTING_DIRECTION_DEBIT",
		2: "POSTING_DIRECTION_CREDIT",
	}
	PostingDirection_value = map[string]int32{
		"POSTING_DIRECTION_UNSPECIFIED": 0,
		"POSTING_DIRECTION_DEBIT":       1,
		"POSTING_DIRECTION_CREDIT":      2,
	}
)

func (x PostingDirection) Enum() *PostingDirection {
	p := new(PostingDirection)
	*p = x
	return p
}

func (x PostingDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostingDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_openpay_v1_ledger_proto_enumTypes[1].Descriptor()
}

func (PostingDirection) Type() protoreflect.EnumType {
	return &file_proto_openpay_v1_ledger_proto_enumTypes[1]
}

func (x PostingDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostingDirection.Descriptor instead.
func (PostingDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{1}
}

type LedgerCheckStatus int32

const (
	LedgerCheckStatus_LEDGER_CHECK_STATUS_UNSPECIFIED LedgerCheckStatus = 0
	// Every invariant held.
	LedgerCheckStatus_LEDGER_CHECK_STATUS_OK LedgerCheckStatus = 1
	// At least one invariant was broken. Never fixed automatically.
	LedgerCheckStatus_LEDGER_CHECK_STATUS_DRIFT LedgerCheckStatus = 2
	// The check itself could not complete, so nothing is known.
	LedgerCheckStatus_LEDGER_CHECK_STATUS_ERROR LedgerCheckStatus = 3
)

// Enum value maps for LedgerCheckStatus.
var (
	LedgerCheckStatus_name = map[int32]string{
		0: "LEDGER_CHECK_STATUS_UNSPECIFIED",
		1: "LEDGER_CHECK_STATUS_OK",
		2: "LEDGER_CHECK_STATUS_DRIFT",
		3: "LEDGER_CHECK_STATUS_ERROR",
	}
	LedgerCheckStatus_value = map[string]int32{
		"LEDGER_CHECK_STATUS_UNSPECIFIED": 0,
		"LEDGER_CHECK_STATUS_OK":          1,
		"LEDGER_CHECK_STATUS_DRIFT":       2,
		"LEDGER_CHECK_STATUS_ERROR":       3,
	}
)

func (x LedgerCheckStatus) Enum() *LedgerCheckStatus {
	p := new(LedgerCheckStatus)
	*p = x
	return p
}

func (x LedgerCheckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerCheckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_openpay_v1_ledger_proto_enumTypes[2].Descriptor()
}

func (LedgerCheckStatus) Type() protoreflect.EnumType {
	return &file_proto_openpay_v1_ledger_proto_enumTypes[2]
}

func (x LedgerCheckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerCheckStatus.Descriptor instead.
func (LedgerCheckStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{2}
}

type LedgerBalance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the account holds, in its natural direction.
	Balance int64 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	// Reserved by active holds and not yet posted.
	Held int64 `protobuf:"varint,2,opt,name=held,proto3" json:"held,omitempty"`
	// balance - held: what can still be spent.
	Available     int64 `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerBalance) Reset() {
	*x = LedgerBalance{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerBalance) ProtoMessage() {}

func (x *LedgerBalance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerBalance.ProtoReflect.Descriptor instead.
func (*LedgerBalance) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *LedgerBalance) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *LedgerBalance) GetHeld() int64 {
	if x != nil {
		return x.Held
	}
	return 0
}

func (x *LedgerBalance) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

type LedgerAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// e.g. income:zshala:product_sales, psp:razorpay:receivable.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Empty for platform accounts, which belong to no product.
	ProductId string            `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Type      LedgerAccountType `protobuf:"varint,4,opt,name=type,proto3,enum=v1.LedgerAccountType" json:"type,omitempty"`
	Currency  string            `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// platform, customer, provider or merchant.
	OwnerKind     string `protobuf:"bytes,6,opt,name=owner_kind,json=ownerKind,proto3" json:"owner_kind,omitempty"`
	OwnerId       string `protobuf:"bytes,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	AllowNegative bool   `protobuf:"varint,8,opt,name=allow_negative,json=allowNegative,proto3" json:"allow_negative,omitempty"`
	// active or closed.
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Balance       *LedgerBalance         `protobuf:"bytes,10,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerAccount) Reset() {
	*x = LedgerAccount{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerAccount) ProtoMessage() {}

func (x *LedgerAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerAccount.ProtoReflect.Descriptor instead.
func (*LedgerAccount) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *LedgerAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LedgerAccount) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LedgerAccount) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *LedgerAccount) GetType() LedgerAccountType {
	if x != nil {
		return x.Type
	}
	return LedgerAccountType_LEDGER_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *LedgerAccount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *LedgerAccount) GetOwnerKind() string {
	if x != nil {
		return x.OwnerKind
	}
	return ""
}

func (x *LedgerAccount) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *LedgerAccount) GetAllowNegative() bool {
	if x != nil {
		return x.AllowNegative
	}
	return false
}

func (x *LedgerAccount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LedgerAccount) GetBalance() *LedgerBalance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *LedgerAccount) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetLedgerAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An account id (acc_…) or an account code (anything containing ':').
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerAccountRequest) Reset() {
	*x = GetLedgerAccountRequest{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerAccountRequest) ProtoMessage() {}

func (x *GetLedgerAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerAccountRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *GetLedgerAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLedgerAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *LedgerAccount         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerAccountResponse) Reset() {
	*x = GetLedgerAccountResponse{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerAccountResponse) ProtoMessage() {}

func (x *GetLedgerAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerAccountResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *GetLedgerAccountResponse) GetAccount() *LedgerAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListLedgerAccountsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Limit  int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Only this product's accounts.
	ProductId string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// Only accounts belonging to no product. Cannot be combined with product_id.
	PlatformOnly bool              `protobuf:"varint,4,opt,name=platform_only,json=platformOnly,proto3" json:"platform_only,omitempty"`
	Type         LedgerAccountType `protobuf:"varint,5,opt,name=type,proto3,enum=v1.LedgerAccountType" json:"type,omitempty"`
	// Prefix of the account code, e.g. "psp:" or "income:zshala:".
	CodePrefix    string `protobuf:"bytes,6,opt,name=code_prefix,json=codePrefix,proto3" json:"code_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerAccountsRequest) Reset() {
	*x = ListLedgerAccountsRequest{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerAccountsRequest) ProtoMessage() {}

func (x *ListLedgerAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListLedgerAccountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *ListLedgerAccountsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListLedgerAccountsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListLedgerAccountsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ListLedgerAccountsRequest) GetPlatformOnly() bool {
	if x != nil {
		return x.PlatformOnly
	}
	return false
}

func (x *ListLedgerAccountsRequest) GetType() LedgerAccountType {
	if x != nil {
		return x.Type
	}
	return LedgerAccountType_LEDGER_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *ListLedgerAccountsRequest) GetCodePrefix() string {
	if x != nil {
		return x.CodePrefix
	}
	return ""
}

type ListLedgerAccountsResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accounts []*LedgerAccount       `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	// Size of the whole filtered set, not of this page.
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerAccountsResponse) Reset() {
	*x = ListLedgerAccountsResponse{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerAccountsResponse) ProtoMessage() {}

func (x *ListLedgerAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListLedgerAccountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *ListLedgerAccountsResponse) GetAccounts() []*LedgerAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *ListLedgerAccountsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// One line of an account statement: a posting, with enough of its journal to
// say why the money moved.
type StatementEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JournalId         string                 `protobuf:"bytes,1,opt,name=journal_id,json=journalId,proto3" json:"journal_id,omitempty"`
	JournalExternalId string                 `protobuf:"bytes,2,opt,name=journal_external_id,json=journalExternalId,proto3" json:"journal_external_id,omitempty"`
	JournalKind       string                 `protobuf:"bytes,3,opt,name=journal_kind,json=journalKind,proto3" json:"journal_kind,omitempty"`
	Memo              string                 `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	Direction         PostingDirection       `protobuf:"varint,5,opt,name=direction,proto3,enum=v1.PostingDirection" json:"direction,omitempty"`
	Amount            int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	// Effect on this account's natural balance: positive when it grew.
	Change int64 `protobuf:"varint,7,opt,name=change,proto3" json:"change,omitempty"`
	// The account's natural balance immediately after this posting.
	BalanceAfter  int64                  `protobuf:"varint,8,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	PostedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatementEntry) Reset() {
	*x = StatementEntry{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatementEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatementEntry) ProtoMessage() {}

func (x *StatementEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatementEntry.ProtoReflect.Descriptor instead.
func (*StatementEntry) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *StatementEntry) GetJournalId() string {
	if x != nil {
		return x.JournalId
	}
	return ""
}

func (x *StatementEntry) GetJournalExternalId() string {
	if x != nil {
		return x.JournalExternalId
	}
	return ""
}

func (x *StatementEntry) GetJournalKind() string {
	if x != nil {
		return x.JournalKind
	}
	return ""
}

func (x *StatementEntry) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *StatementEntry) GetDirection() PostingDirection {
	if x != nil {
		return x.Direction
	}
	return PostingDirection_POSTING_DIRECTION_UNSPECIFIED
}

func (x *StatementEntry) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StatementEntry) GetChange() int64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *StatementEntry) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *StatementEntry) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

type GetAccountStatementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An account id or code, as for GetLedgerAccount.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit     int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// next_cursor from the previous page. Empty for the newest entries.
	Cursor        string `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountStatementRequest) Reset() {
	*x = GetAccountStatementRequest{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountStatementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStatementRequest) ProtoMessage() {}

func (x *GetAccountStatementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStatementRequest.ProtoReflect.Descriptor instead.
func (*GetAccountStatementRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountStatementRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountStatementRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAccountStatementRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetAccountStatementResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Account *LedgerAccount         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// Newest first.
	Entries []*StatementEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	// Pass as cursor for the next, older page. Empty on the last page.
	NextCursor    string `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountStatementResponse) Reset() {
	*x = GetAccountStatementResponse{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountStatementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStatementResponse) ProtoMessage() {}

func (x *GetAccountStatementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStatementResponse.ProtoReflect.Descriptor instead.
func (*GetAccountStatementResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *GetAccountStatementResponse) GetAccount() *LedgerAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *GetAccountStatementResponse) GetEntries() []*StatementEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetAccountStatementResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type JournalPosting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountCode   string                 `protobuf:"bytes,2,opt,name=account_code,json=accountCode,proto3" json:"account_code,omitempty"`
	Direction     PostingDirection       `protobuf:"varint,3,opt,name=direction,proto3,enum=v1.PostingDirection" json:"direction,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalPosting) Reset() {
	*x = JournalPosting{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalPosting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalPosting) ProtoMessage() {}

func (x *JournalPosting) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalPosting.ProtoReflect.Descriptor instead.
func (*JournalPosting) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *JournalPosting) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *JournalPosting) GetAccountCode() string {
	if x != nil {
		return x.AccountCode
	}
	return ""
}

func (x *JournalPosting) GetDirection() PostingDirection {
	if x != nil {
		return x.Direction
	}
	return PostingDirection_POSTING_DIRECTION_UNSPECIFIED
}

func (x *JournalPosting) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *JournalPosting) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Journal struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Kind       string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	ProductId  string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SourceKind string                 `protobuf:"bytes,5,opt,name=source_kind,json=sourceKind,proto3" json:"source_kind,omitempty"`
	SourceId   string                 `protobuf:"bytes,6,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// The journal this one reverses, if it is a correction.
	ReversesJournalId string                 `protobuf:"bytes,7,opt,name=reverses_journal_id,json=reversesJournalId,proto3" json:"reverses_journal_id,omitempty"`
	Memo              string                 `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	Postings          []*JournalPosting      `protobuf:"bytes,9,rep,name=postings,proto3" json:"postings,omitempty"`
	PostedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Journal) Reset() {
	*x = Journal{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Journal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Journal) ProtoMessage() {}

func (x *Journal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Journal.ProtoReflect.Descriptor instead.
func (*Journal) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *Journal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Journal) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Journal) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Journal) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Journal) GetSourceKind() string {
	if x != nil {
		return x.SourceKind
	}
	return ""
}

func (x *Journal) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Journal) GetReversesJournalId() string {
	if x != nil {
		return x.ReversesJournalId
	}
	return ""
}

func (x *Journal) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Journal) GetPostings() []*JournalPosting {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *Journal) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

type GetJournalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A journal id (jrn_…) or its external id (anything containing ':').
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJournalRequest) Reset() {
	*x = GetJournalRequest{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJournalRequest) ProtoMessage() {}

func (x *GetJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJournalRequest.ProtoReflect.Descriptor instead.
func (*GetJournalRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *GetJournalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetJournalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Journal       *Journal               `protobuf:"bytes,1,opt,name=journal,proto3" json:"journal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJournalResponse) Reset() {
	*x = GetJournalResponse{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJournalResponse) ProtoMessage() {}

func (x *GetJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJournalResponse.ProtoReflect.Descriptor instead.
func (*GetJournalResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *GetJournalResponse) GetJournal() *Journal {
	if x != nil {
		return x.Journal
	}
	return nil
}

type TrialBalanceLine struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AccountId   string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountCode string                 `protobuf:"bytes,2,opt,name=account_code,json=accountCode,proto3" json:"account_code,omitempty"`
	Type        LedgerAccountType      `protobuf:"varint,3,opt,name=type,proto3,enum=v1.LedgerAccountType" json:"type,omitempty"`
	ProductId   string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Currency    string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Debits      int64                  `protobuf:"varint,6,opt,name=debits,proto3" json:"debits,omitempty"`
	Credits     int64                  `protobuf:"varint,7,opt,name=credits,proto3" json:"credits,omitempty"`
	// debits - credits.
	RawBalance int64 `protobuf:"varint,8,opt,name=raw_balance,json=rawBalance,proto3" json:"raw_balance,omitempty"`
	// The balance in the account's natural direction.
	Balance       int64 `protobuf:"varint,9,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrialBalanceLine) Reset() {
	*x = TrialBalanceLine{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrialBalanceLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrialBalanceLine) ProtoMessage() {}

func (x *TrialBalanceLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrialBalanceLine.ProtoReflect.Descriptor instead.
func (*TrialBalanceLine) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *TrialBalanceLine) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *TrialBalanceLine) GetAccountCode() string {
	if x != nil {
		return x.AccountCode
	}
	return ""
}

func (x *TrialBalanceLine) GetType() LedgerAccountType {
	if x != nil {
		return x.Type
	}
	return LedgerAccountType_LEDGER_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *TrialBalanceLine) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *TrialBalanceLine) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TrialBalanceLine) GetDebits() int64 {
	if x != nil {
		return x.Debits
	}
	return 0
}

func (x *TrialBalanceLine) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *TrialBalanceLine) GetRawBalance() int64 {
	if x != nil {
		return x.RawBalance
	}
	return 0
}

func (x *TrialBalanceLine) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type TrialBalanceTotal struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Currency string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Debits   int64                  `protobuf:"varint,2,opt,name=debits,proto3" json:"debits,omitempty"`
	Credits  int64                  `protobuf:"varint,3,opt,name=credits,proto3" json:"credits,omitempty"`
	// For the whole platform this must be zero. For one product it generally is
	// not: the other side of its revenue sits in platform accounts.
	Difference    int64 `protobuf:"varint,4,opt,name=difference,proto3" json:"difference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrialBalanceTotal) Reset() {
	*x = TrialBalanceTotal{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrialBalanceTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrialBalanceTotal) ProtoMessage() {}

func (x *TrialBalanceTotal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrialBalanceTotal.ProtoReflect.Descriptor instead.
func (*TrialBalanceTotal) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *TrialBalanceTotal) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TrialBalanceTotal) GetDebits() int64 {
	if x != nil {
		return x.Debits
	}
	return 0
}

func (x *TrialBalanceTotal) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *TrialBalanceTotal) GetDifference() int64 {
	if x != nil {
		return x.Difference
	}
	return 0
}

type GetTrialBalanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only this product's accounts. Empty for the whole platform.
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// Balances as they stood at this moment. Empty for now.
	AsOf *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	// Include accounts that have never been posted to.
	IncludeEmpty  bool `protobuf:"varint,3,opt,name=include_empty,json=includeEmpty,proto3" json:"include_empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrialBalanceRequest) Reset() {
	*x = GetTrialBalanceRequest{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrialBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrialBalanceRequest) ProtoMessage() {}

func (x *GetTrialBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrialBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetTrialBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{15}
}

func (x *GetTrialBalanceRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetTrialBalanceRequest) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

func (x *GetTrialBalanceRequest) GetIncludeEmpty() bool {
	if x != nil {
		return x.IncludeEmpty
	}
	return false
}

type GetTrialBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []*TrialBalanceLine    `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Totals        []*TrialBalanceTotal   `protobuf:"bytes,2,rep,name=totals,proto3" json:"totals,omitempty"`
	AsOf          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrialBalanceResponse) Reset() {
	*x = GetTrialBalanceResponse{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrialBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrialBalanceResponse) ProtoMessage() {}

func (x *GetTrialBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrialBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetTrialBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{16}
}

func (x *GetTrialBalanceResponse) GetLines() []*TrialBalanceLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *GetTrialBalanceResponse) GetTotals() []*TrialBalanceTotal {
	if x != nil {
		return x.Totals
	}
	return nil
}

func (x *GetTrialBalanceResponse) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

type LedgerCheckFinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which invariant, e.g. journal_unbalanced, balance_drift.
	Invariant string `protobuf:"bytes,1,opt,name=invariant,proto3" json:"invariant,omitempty"`
	// What it concerns: an account code, journal external id, or currency.
	Subject       string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Expected      int64  `protobuf:"varint,3,opt,name=expected,proto3" json:"expected,omitempty"`
	Actual        int64  `protobuf:"varint,4,opt,name=actual,proto3" json:"actual,omitempty"`
	Detail        string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerCheckFinding) Reset() {
	*x = LedgerCheckFinding{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerCheckFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerCheckFinding) ProtoMessage() {}

func (x *LedgerCheckFinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerCheckFinding.ProtoReflect.Descriptor instead.
func (*LedgerCheckFinding) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{17}
}

func (x *LedgerCheckFinding) GetInvariant() string {
	if x != nil {
		return x.Invariant
	}
	return ""
}

func (x *LedgerCheckFinding) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *LedgerCheckFinding) GetExpected() int64 {
	if x != nil {
		return x.Expected
	}
	return 0
}

func (x *LedgerCheckFinding) GetActual() int64 {
	if x != nil {
		return x.Actual
	}
	return 0
}

func (x *LedgerCheckFinding) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type LedgerCheckRun struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status LedgerCheckStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=v1.LedgerCheckStatus" json:"status,omitempty"`
	// scheduled or manual.
	Trigger string `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	// Who asked, for a manual run.
	TriggeredBy string                `protobuf:"bytes,4,opt,name=triggered_by,json=triggeredBy,proto3" json:"triggered_by,omitempty"`
	Findings    []*LedgerCheckFinding `protobuf:"bytes,5,rep,name=findings,proto3" json:"findings,omitempty"`
	// Set when the findings list was cut short; the ledger has more.
	Truncated     bool                   `protobuf:"varint,6,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerCheckRun) Reset() {
	*x = LedgerCheckRun{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerCheckRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerCheckRun) ProtoMessage() {}

func (x *LedgerCheckRun) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerCheckRun.ProtoReflect.Descriptor instead.
func (*LedgerCheckRun) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{18}
}

func (x *LedgerCheckRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LedgerCheckRun) GetStatus() LedgerCheckStatus {
	if x != nil {
		return x.Status
	}
	return LedgerCheckStatus_LEDGER_CHECK_STATUS_UNSPECIFIED
}

func (x *LedgerCheckRun) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *LedgerCheckRun) GetTriggeredBy() string {
	if x != nil {
		return x.TriggeredBy
	}
	return ""
}

func (x *LedgerCheckRun) GetFindings() []*LedgerCheckFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *LedgerCheckRun) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *LedgerCheckRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LedgerCheckRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *LedgerCheckRun) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type RunLedgerCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunLedgerCheckRequest) Reset() {
	*x = RunLedgerCheckRequest{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunLedgerCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunLedgerCheckRequest) ProtoMessage() {}

func (x *RunLedgerCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunLedgerCheckRequest.ProtoReflect.Descriptor instead.
func (*RunLedgerCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{19}
}

type RunLedgerCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *LedgerCheckRun        `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunLedgerCheckResponse) Reset() {
	*x = RunLedgerCheckResponse{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunLedgerCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunLedgerCheckResponse) ProtoMessage() {}

func (x *RunLedgerCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunLedgerCheckResponse.ProtoReflect.Descriptor instead.
func (*RunLedgerCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{20}
}

func (x *RunLedgerCheckResponse) GetRun() *LedgerCheckRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type ListLedgerCheckRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerCheckRunsRequest) Reset() {
	*x = ListLedgerCheckRunsRequest{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerCheckRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerCheckRunsRequest) ProtoMessage() {}

func (x *ListLedgerCheckRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerCheckRunsRequest.ProtoReflect.Descriptor instead.
func (*ListLedgerCheckRunsRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{21}
}

func (x *ListLedgerCheckRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLedgerCheckRunsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Newest first.
	Runs          []*LedgerCheckRun `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerCheckRunsResponse) Reset() {
	*x = ListLedgerCheckRunsResponse{}
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerCheckRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerCheckRunsResponse) ProtoMessage() {}

func (x *ListLedgerCheckRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_ledger_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerCheckRunsResponse.ProtoReflect.Descriptor instead.
func (*ListLedgerCheckRunsResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_ledger_proto_rawDescGZIP(), []int{22}
}

func (x *ListLedgerCheckRunsResponse) GetRuns() []*LedgerCheckRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

var File_proto_openpay_v1_ledger_proto protoreflect.FileDescriptor

const file_proto_openpay_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/openpay/v1/ledger.proto\x12\x02v1\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n" +
	"\rLedgerBalance\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance\x12\x12\n" +
	"\x04held\x18\x02 \x01(\x03R\x04held\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\x03R\tavailable\"\xfa\x02\n" +
	"\rLedgerAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.v1.LedgerAccountTypeR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"owner_kind\x18\x06 \x01(\tR\townerKind\x12\x19\n" +
	"\bowner_id\x18\a \x01(\tR\aownerId\x12%\n" +
	"\x0eallow_negative\x18\b \x01(\bR\rallowNegative\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12+\n" +
	"\abalance\x18\n" +
	" \x01(\v2\x11.v1.LedgerBalanceR\abalance\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"5\n" +
	"\x17GetLedgerAccountRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xac\x02R\x02id\"G\n" +
	"\x18GetLedgerAccountResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.v1.LedgerAccountR\aaccount\"\x81\x02\n" +
	"\x19ListLedgerAccountsRequest\x12\x1f\n" +
	"\x05limit\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\x05limit\x12\x1f\n" +
	"\x06offset\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x06offset\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12#\n" +
	"\rplatform_only\x18\x04 \x01(\bR\fplatformOnly\x123\n" +
	"\x04type\x18\x05 \x01(\x0e2\x15.v1.LedgerAccountTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04type\x12)\n" +
	"\vcode_prefix\x18\x06 \x01(\tB\b\xfaB\x05r\x03\x18\xac\x02R\n" +
	"codePrefix\"a\n" +
	"\x1aListLedgerAccountsResponse\x12-\n" +
	"\baccounts\x18\x01 \x03(\v2\x11.v1.LedgerAccountR\baccounts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xd8\x02\n" +
	"\x0eStatementEntry\x12\x1d\n" +
	"\n" +
	"journal_id\x18\x01 \x01(\tR\tjournalId\x12.\n" +
	"\x13journal_external_id\x18\x02 \x01(\tR\x11journalExternalId\x12!\n" +
	"\fjournal_kind\x18\x03 \x01(\tR\vjournalKind\x12\x12\n" +
	"\x04memo\x18\x04 \x01(\tR\x04memo\x122\n" +
	"\tdirection\x18\x05 \x01(\x0e2\x14.v1.PostingDirectionR\tdirection\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06change\x18\a \x01(\x03R\x06change\x12#\n" +
	"\rbalance_after\x18\b \x01(\x03R\fbalanceAfter\x127\n" +
	"\tposted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\"\x89\x01\n" +
	"\x1aGetAccountStatementRequest\x12)\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xac\x02R\taccountId\x12\x1f\n" +
	"\x05limit\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\x05limit\x12\x1f\n" +
	"\x06cursor\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x182R\x06cursor\"\x99\x01\n" +
	"\x1bGetAccountStatementResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.v1.LedgerAccountR\aaccount\x12,\n" +
	"\aentries\x18\x02 \x03(\v2\x12.v1.StatementEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\"\xba\x01\n" +
	"\x0eJournalPosting\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccount_code\x18\x02 \x01(\tR\vaccountCode\x122\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x14.v1.PostingDirectionR\tdirection\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"\xd8\x02\n" +
	"\aJournal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x12\x1f\n" +
	"\vsource_kind\x18\x05 \x01(\tR\n" +
	"sourceKind\x12\x1b\n" +
	"\tsource_id\x18\x06 \x01(\tR\bsourceId\x12.\n" +
	"\x13reverses_journal_id\x18\a \x01(\tR\x11reversesJournalId\x12\x12\n" +
	"\x04memo\x18\b \x01(\tR\x04memo\x12.\n" +
	"\bpostings\x18\t \x03(\v2\x12.v1.JournalPostingR\bpostings\x127\n" +
	"\tposted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\"/\n" +
	"\x11GetJournalRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xac\x02R\x02id\";\n" +
	"\x12GetJournalResponse\x12%\n" +
	"\ajournal\x18\x01 \x01(\v2\v.v1.JournalR\ajournal\"\xa7\x02\n" +
	"\x10TrialBalanceLine\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccount_code\x18\x02 \x01(\tR\vaccountCode\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.v1.LedgerAccountTypeR\x04type\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06debits\x18\x06 \x01(\x03R\x06debits\x12\x18\n" +
	"\acredits\x18\a \x01(\x03R\acredits\x12\x1f\n" +
	"\vraw_balance\x18\b \x01(\x03R\n" +
	"rawBalance\x12\x18\n" +
	"\abalance\x18\t \x01(\x03R\abalance\"\x81\x01\n" +
	"\x11TrialBalanceTotal\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06debits\x18\x02 \x01(\x03R\x06debits\x12\x18\n" +
	"\acredits\x18\x03 \x01(\x03R\acredits\x12\x1e\n" +
	"\n" +
	"difference\x18\x04 \x01(\x03R\n" +
	"difference\"\x8d\x01\n" +
	"\x16GetTrialBalanceRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12/\n" +
	"\x05as_of\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf\x12#\n" +
	"\rinclude_empty\x18\x03 \x01(\bR\fincludeEmpty\"\xa5\x01\n" +
	"\x17GetTrialBalanceResponse\x12*\n" +
	"\x05lines\x18\x01 \x03(\v2\x14.v1.TrialBalanceLineR\x05lines\x12-\n" +
	"\x06totals\x18\x02 \x03(\v2\x15.v1.TrialBalanceTotalR\x06totals\x12/\n" +
	"\x05as_of\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf\"\x98\x01\n" +
	"\x12LedgerCheckFinding\x12\x1c\n" +
	"\tinvariant\x18\x01 \x01(\tR\tinvariant\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1a\n" +
	"\bexpected\x18\x03 \x01(\x03R\bexpected\x12\x16\n" +
	"\x06actual\x18\x04 \x01(\x03R\x06actual\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\"\xec\x02\n" +
	"\x0eLedgerCheckRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.v1.LedgerCheckStatusR\x06status\x12\x18\n" +
	"\atrigger\x18\x03 \x01(\tR\atrigger\x12!\n" +
	"\ftriggered_by\x18\x04 \x01(\tR\vtriggeredBy\x122\n" +
	"\bfindings\x18\x05 \x03(\v2\x16.v1.LedgerCheckFindingR\bfindings\x12\x1c\n" +
	"\ttruncated\x18\x06 \x01(\bR\ttruncated\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\x17\n" +
	"\x15RunLedgerCheckRequest\">\n" +
	"\x16RunLedgerCheckResponse\x12$\n" +
	"\x03run\x18\x01 \x01(\v2\x12.v1.LedgerCheckRunR\x03run\"=\n" +
	"\x1aListLedgerCheckRunsRequest\x12\x1f\n" +
	"\x05limit\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\x05limit\"E\n" +
	"\x1bListLedgerCheckRunsResponse\x12&\n" +
	"\x04runs\x18\x01 \x03(\v2\x12.v1.LedgerCheckRunR\x04runs*\xdb\x01\n" +
	"\x11LedgerAccountType\x12#\n" +
	"\x1fLEDGER_ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19LEDGER_ACCOUNT_TYPE_ASSET\x10\x01\x12!\n" +
	"\x1dLEDGER_ACCOUNT_TYPE_LIABILITY\x10\x02\x12\x1e\n" +
	"\x1aLEDGER_ACCOUNT_TYPE_EQUITY\x10\x03\x12\x1e\n" +
	"\x1aLEDGER_ACCOUNT_TYPE_INCOME\x10\x04\x12\x1f\n" +
	"\x1bLEDGER_ACCOUNT_TYPE_EXPENSE\x10\x05*p\n" +
	"\x10PostingDirection\x12!\n" +
	"\x1dPOSTING_DIRECTION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17POSTING_DIRECTION_DEBIT\x10\x01\x12\x1c\n" +
	"\x18POSTING_DIRECTION_CREDIT\x10\x02*\x92\x01\n" +
	"\x11LedgerCheckStatus\x12#\n" +
	"\x1fLEDGER_CHECK_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16LEDGER_CHECK_STATUS_OK\x10\x01\x12\x1d\n" +
	"\x19LEDGER_CHECK_STATUS_DRIFT\x10\x02\x12\x1d\n" +
	"\x19LEDGER_CHECK_STATUS_ERROR\x10\x03B\x0eZ\f./openpay_v1b\x06proto3"

var (
	file_proto_openpay_v1_ledger_proto_rawDescOnce sync.Once
	file_proto_openpay_v1_ledger_proto_rawDescData []byte
)

func file_proto_openpay_v1_ledger_proto_rawDescGZIP() []byte {
	file_proto_openpay_v1_ledger_proto_rawDescOnce.Do(func() {
		file_proto_openpay_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_openpay_v1_ledger_proto_rawDesc), len(file_proto_openpay_v1_ledger_proto_rawDesc)))
	})
	return file_proto_openpay_v1_ledger_proto_rawDescData
}

var file_proto_openpay_v1_ledger_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_openpay_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_openpay_v1_ledger_proto_goTypes = []any{
	(LedgerAccountType)(0),              // 0: v1.LedgerAccountType
	(PostingDirection)(0),               // 1: v1.PostingDirection
	(LedgerCheckStatus)(0),              // 2: v1.LedgerCheckStatus
	(*LedgerBalance)(nil),               // 3: v1.LedgerBalance
	(*LedgerAccount)(nil),               // 4: v1.LedgerAccount
	(*GetLedgerAccountRequest)(nil),     // 5: v1.GetLedgerAccountRequest
	(*GetLedgerAccountResponse)(nil),    // 6: v1.GetLedgerAccountResponse
	(*ListLedgerAccountsRequest)(nil),   // 7: v1.ListLedgerAccountsRequest
	(*ListLedgerAccountsResponse)(nil),  // 8: v1.ListLedgerAccountsResponse
	(*StatementEntry)(nil),              // 9: v1.StatementEntry
	(*GetAccountStatementRequest)(nil),  // 10: v1.GetAccountStatementRequest
	(*GetAccountStatementResponse)(nil), // 11: v1.GetAccountStatementResponse
	(*JournalPosting)(nil),              // 12: v1.JournalPosting
	(*Journal)(nil),                     // 13: v1.Journal
	(*GetJournalRequest)(nil),           // 14: v1.GetJournalRequest
	(*GetJournalResponse)(nil),          // 15: v1.GetJournalResponse
	(*TrialBalanceLine)(nil),            // 16: v1.TrialBalanceLine
	(*TrialBalanceTotal)(nil),           // 17: v1.TrialBalanceTotal
	(*GetTrialBalanceRequest)(nil),      // 18: v1.GetTrialBalanceRequest
	(*GetTrialBalanceResponse)(nil),     // 19: v1.GetTrialBalanceResponse
	(*LedgerCheckFinding)(nil),          // 20: v1.LedgerCheckFinding
	(*LedgerCheckRun)(nil),              // 21: v1.LedgerCheckRun
	(*RunLedgerCheckRequest)(nil),       // 22: v1.RunLedgerCheckRequest
	(*RunLedgerCheckResponse)(nil),      // 23: v1.RunLedgerCheckResponse
	(*ListLedgerCheckRunsRequest)(nil),  // 24: v1.ListLedgerCheckRunsRequest
	(*ListLedgerCheckRunsResponse)(nil), // 25: v1.ListLedgerCheckRunsResponse
	(*timestamppb.Timestamp)(nil),       // 26: google.protobuf.Timestamp
}
var file_proto_openpay_v1_ledger_proto_depIdxs = []int32{
	0,  // 0: v1.LedgerAccount.type:type_name -> v1.LedgerAccountType
	3,  // 1: v1.LedgerAccount.balance:type_name -> v1.LedgerBalance
	26, // 2: v1.LedgerAccount.created_at:type_name -> google.protobuf.Timestamp
	4,  // 3: v1.GetLedgerAccountResponse.account:type_name -> v1.LedgerAccount
	0,  // 4: v1.ListLedgerAccountsRequest.type:type_name -> v1.LedgerAccountType
	4,  // 5: v1.ListLedgerAccountsResponse.accounts:type_name -> v1.LedgerAccount
	1,  // 6: v1.StatementEntry.direction:type_name -> v1.PostingDirection
	26, // 7: v1.StatementEntry.posted_at:type_name -> google.protobuf.Timestamp
	4,  // 8: v1.GetAccountStatementResponse.account:type_name -> v1.LedgerAccount
	9,  // 9: v1.GetAccountStatementResponse.entries:type_name -> v1.StatementEntry
	1,  // 10: v1.JournalPosting.direction:type_name -> v1.PostingDirection
	12, // 11: v1.Journal.postings:type_name -> v1.JournalPosting
	26, // 12: v1.Journal.posted_at:type_name -> google.protobuf.Timestamp
	13, // 13: v1.GetJournalResponse.journal:type_name -> v1.Journal
	0,  // 14: v1.TrialBalanceLine.type:type_name -> v1.LedgerAccountType
	26, // 15: v1.GetTrialBalanceRequest.as_of:type_name -> google.protobuf.Timestamp
	16, // 16: v1.GetTrialBalanceResponse.lines:type_name -> v1.TrialBalanceLine
	17, // 17: v1.GetTrialBalanceResponse.totals:type_name -> v1.TrialBalanceTotal
	26, // 18: v1.GetTrialBalanceResponse.as_of:type_name -> google.protobuf.Timestamp
	2,  // 19: v1.LedgerCheckRun.status:type_name -> v1.LedgerCheckStatus
	20, // 20: v1.LedgerCheckRun.findings:type_name -> v1.LedgerCheckFinding
	26, // 21: v1.LedgerCheckRun.started_at:type_name -> google.protobuf.Timestamp
	26, // 22: v1.LedgerCheckRun.finished_at:type_name -> google.protobuf.Timestamp
	21, // 23: v1.RunLedgerCheckResponse.run:type_name -> v1.LedgerCheckRun
	21, // 24: v1.ListLedgerCheckRunsResponse.runs:type_name -> v1.LedgerCheckRun
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_openpay_v1_ledger_proto_init() }
func file_proto_openpay_v1_ledger_proto_init() {
	if File_proto_openpay_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_openpay_v1_ledger_proto_rawDesc), len(file_proto_openpay_v1_ledger_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_openpay_v1_ledger_proto_goTypes,
		DependencyIndexes: file_proto_openpay_v1_ledger_proto_depIdxs,
		EnumInfos:         file_proto_openpay_v1_ledger_proto_enumTypes,
		MessageInfos:      file_proto_openpay_v1_ledger_proto_msgTypes,
	}.Build()
	File_proto_openpay_v1_ledger_proto = out.File
	file_proto_openpay_v1_ledger_proto_goTypes = nil
	file_proto_openpay_v1_ledger_proto_depIdxs = nil
}
