// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/openpay/v1/openpay.proto

package openpay_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenPay_Ping_FullMethodName = "/v1.OpenPay/Ping"
)

// OpenPayClient is the client API for OpenPay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenPayClient interface {
	// Ping is a simple GET request that returns a Pong message.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type openPayClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenPayClient(cc grpc.ClientConnInterface) OpenPayClient {
	return &openPayClient{cc}
}

func (c *openPayClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, OpenPay_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenPayServer is the server API for OpenPay service.
// All implementations must embed UnimplementedOpenPayServer
// for forward compatibility.
type OpenPayServer interface {
	// Ping is a simple GET request that returns a Pong message.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedOpenPayServer()
}

// UnimplementedOpenPayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenPayServer struct{}

func (UnimplementedOpenPayServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOpenPayServer) mustEmbedUnimplementedOpenPayServer() {}
func (UnimplementedOpenPayServer) testEmbeddedByValue()                 {}

// UnsafeOpenPayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenPayServer will
// result in compilation errors.
type UnsafeOpenPayServer interface {
	mustEmbedUnimplementedOpenPayServer()
}

func RegisterOpenPayServer(s grpc.ServiceRegistrar, srv OpenPayServer) {
	// If the following call pancis, it indicates UnimplementedOpenPayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenPay_ServiceDesc, srv)
}

func _OpenPay_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenPayServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenPay_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenPayServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpenPay_ServiceDesc is the grpc.ServiceDesc for OpenPay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenPay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.OpenPay",
	HandlerType: (*OpenPayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _OpenPay_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/openpay/v1/openpay.proto",
}
