// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/openpay/v1/order.proto

package openpay_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	// Waiting for the card share; wallet shares are held.
	OrderStatus_ORDER_STATUS_PENDING_PAYMENT    OrderStatus = 1
	OrderStatus_ORDER_STATUS_PAID               OrderStatus = 2
	OrderStatus_ORDER_STATUS_FAILED             OrderStatus = 3
	OrderStatus_ORDER_STATUS_CANCELLED          OrderStatus = 4
	OrderStatus_ORDER_STATUS_PARTIALLY_REFUNDED OrderStatus = 5
	OrderStatus_ORDER_STATUS_REFUNDED           OrderStatus = 6
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING_PAYMENT",
		2: "ORDER_STATUS_PAID",
		3: "ORDER_STATUS_FAILED",
		4: "ORDER_STATUS_CANCELLED",
		5: "ORDER_STATUS_PARTIALLY_REFUNDED",
		6: "ORDER_STATUS_REFUNDED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":        0,
		"ORDER_STATUS_PENDING_PAYMENT":    1,
		"ORDER_STATUS_PAID":               2,
		"ORDER_STATUS_FAILED":             3,
		"ORDER_STATUS_CANCELLED":          4,
		"ORDER_STATUS_PARTIALLY_REFUNDED": 5,
		"ORDER_STATUS_REFUNDED":           6,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_openpay_v1_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_openpay_v1_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{0}
}

type Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code  string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// For description and reporting only; an order carries what was charged.
	ReferencePrice int64  `protobuf:"varint,4,opt,name=reference_price,json=referencePrice,proto3" json:"reference_price,omitempty"`
	Currency       string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// A reporting label, e.g. gst_18. Never used to compute anything.
	TaxClass      string                 `protobuf:"bytes,6,opt,name=tax_class,json=taxClass,proto3" json:"tax_class,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetReferencePrice() int64 {
	if x != nil {
		return x.ReferencePrice
	}
	return 0
}

func (x *Item) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Item) GetTaxClass() string {
	if x != nil {
		return x.TaxClass
	}
	return ""
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateItemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ReferencePrice int64                  `protobuf:"varint,3,opt,name=reference_price,json=referencePrice,proto3" json:"reference_price,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	TaxClass       string                 `protobuf:"bytes,5,opt,name=tax_class,json=taxClass,proto3" json:"tax_class,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateItemRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateItemRequest) GetReferencePrice() int64 {
	if x != nil {
		return x.ReferencePrice
	}
	return 0
}

func (x *CreateItemRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateItemRequest) GetTaxClass() string {
	if x != nil {
		return x.TaxClass
	}
	return ""
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{3}
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderLine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: a catalogue item of this product.
	ItemId        string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int32  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitAmount    int64  `protobuf:"varint,4,opt,name=unit_amount,json=unitAmount,proto3" json:"unit_amount,omitempty"`
	Amount        int64  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderLine) Reset() {
	*x = OrderLine{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderLine) ProtoMessage() {}

func (x *OrderLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderLine.ProtoReflect.Descriptor instead.
func (*OrderLine) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderLine) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderLine) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrderLine) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderLine) GetUnitAmount() int64 {
	if x != nil {
		return x.UnitAmount
	}
	return 0
}

func (x *OrderLine) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WalletTender struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletTender) Reset() {
	*x = WalletTender{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletTender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletTender) ProtoMessage() {}

func (x *WalletTender) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletTender.ProtoReflect.Descriptor instead.
func (*WalletTender) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *WalletTender) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletTender) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OrderTender struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// wallet or gateway.
	Kind     string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	WalletId string `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Amount   int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// held, captured or released.
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTender) Reset() {
	*x = OrderTender{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTender) ProtoMessage() {}

func (x *OrderTender) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTender.ProtoReflect.Descriptor instead.
func (*OrderTender) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *OrderTender) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OrderTender) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *OrderTender) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderTender) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Order struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalRef string                 `protobuf:"bytes,2,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	InvoiceRef  string                 `protobuf:"bytes,3,opt,name=invoice_ref,json=invoiceRef,proto3" json:"invoice_ref,omitempty"`
	ProductId   string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CustomerId  string                 `protobuf:"bytes,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Currency    string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Subtotal    int64                  `protobuf:"varint,7,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Discount    int64                  `protobuf:"varint,8,opt,name=discount,proto3" json:"discount,omitempty"`
	Tax         int64                  `protobuf:"varint,9,opt,name=tax,proto3" json:"tax,omitempty"`
	Total       int64                  `protobuf:"varint,10,opt,name=total,proto3" json:"total,omitempty"`
	TaxRate     string                 `protobuf:"bytes,11,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	// False when the product sent a bare total: booked gross, flagged here.
	TaxBreakdownProvided bool           `protobuf:"varint,12,opt,name=tax_breakdown_provided,json=taxBreakdownProvided,proto3" json:"tax_breakdown_provided,omitempty"`
	Status               OrderStatus    `protobuf:"varint,13,opt,name=status,proto3,enum=v1.OrderStatus" json:"status,omitempty"`
	FailureReason        string         `protobuf:"bytes,14,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	Lines                []*OrderLine   `protobuf:"bytes,15,rep,name=lines,proto3" json:"lines,omitempty"`
	Tenders              []*OrderTender `protobuf:"bytes,16,rep,name=tenders,proto3" json:"tenders,omitempty"`
	// The card share, and where to send the customer to pay it.
	GatewayAmount int64                  `protobuf:"varint,17,opt,name=gateway_amount,json=gatewayAmount,proto3" json:"gateway_amount,omitempty"`
	PaymentId     string                 `protobuf:"bytes,18,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	CheckoutUrl   string                 `protobuf:"bytes,19,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Refunds       []*OrderRefund         `protobuf:"bytes,23,rep,name=refunds,proto3" json:"refunds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *Order) GetInvoiceRef() string {
	if x != nil {
		return x.InvoiceRef
	}
	return ""
}

func (x *Order) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *Order) GetDiscount() int64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *Order) GetTax() int64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *Order) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Order) GetTaxRate() string {
	if x != nil {
		return x.TaxRate
	}
	return ""
}

func (x *Order) GetTaxBreakdownProvided() bool {
	if x != nil {
		return x.TaxBreakdownProvided
	}
	return false
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Order) GetLines() []*OrderLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Order) GetTenders() []*OrderTender {
	if x != nil {
		return x.Tenders
	}
	return nil
}

func (x *Order) GetGatewayAmount() int64 {
	if x != nil {
		return x.GatewayAmount
	}
	return 0
}

func (x *Order) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Order) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *Order) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Order) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetRefunds() []*OrderRefund {
	if x != nil {
		return x.Refunds
	}
	return nil
}

// An order refund carries its own tax split (plan.md D13). Without one, the
// split is proportional to the order's and tax_breakdown_provided is false.
type OrderRefund struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Subtotal             int64                  `protobuf:"varint,3,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Discount             int64                  `protobuf:"varint,4,opt,name=discount,proto3" json:"discount,omitempty"`
	Tax                  int64                  `protobuf:"varint,5,opt,name=tax,proto3" json:"tax,omitempty"`
	TaxBreakdownProvided bool                   `protobuf:"varint,6,opt,name=tax_breakdown_provided,json=taxBreakdownProvided,proto3" json:"tax_breakdown_provided,omitempty"`
	// source or wallet.
	Destination   string                 `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,8,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	Memo          string                 `protobuf:"bytes,9,opt,name=memo,proto3" json:"memo,omitempty"`
	Parts         []*OrderRefundPart     `protobuf:"bytes,10,rep,name=parts,proto3" json:"parts,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRefund) Reset() {
	*x = OrderRefund{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRefund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRefund) ProtoMessage() {}

func (x *OrderRefund) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRefund.ProtoReflect.Descriptor instead.
func (*OrderRefund) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *OrderRefund) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderRefund) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderRefund) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *OrderRefund) GetDiscount() int64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *OrderRefund) GetTax() int64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *OrderRefund) GetTaxBreakdownProvided() bool {
	if x != nil {
		return x.TaxBreakdownProvided
	}
	return false
}

func (x *OrderRefund) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *OrderRefund) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *OrderRefund) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *OrderRefund) GetParts() []*OrderRefundPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *OrderRefund) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// How much of a refund went back through one tender, and where.
type OrderRefundPart struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Amount int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Credited to this wallet…
	WalletId string `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	// …or returned to the card through this payment refund.
	RefundId      string `protobuf:"bytes,3,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRefundPart) Reset() {
	*x = OrderRefundPart{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRefundPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRefundPart) ProtoMessage() {}

func (x *OrderRefundPart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRefundPart.ProtoReflect.Descriptor instead.
func (*OrderRefundPart) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{10}
}

func (x *OrderRefundPart) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderRefundPart) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *OrderRefundPart) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

type RefundOrderRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// The refund's own split. Leave false to have it split proportionally.
	TaxBreakdownProvided bool  `protobuf:"varint,3,opt,name=tax_breakdown_provided,json=taxBreakdownProvided,proto3" json:"tax_breakdown_provided,omitempty"`
	Subtotal             int64 `protobuf:"varint,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Discount             int64 `protobuf:"varint,5,opt,name=discount,proto3" json:"discount,omitempty"`
	Tax                  int64 `protobuf:"varint,6,opt,name=tax,proto3" json:"tax,omitempty"`
	// Empty uses the product's default.
	Destination   string `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	ReasonCode    string `protobuf:"bytes,8,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	Memo          string `protobuf:"bytes,9,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundOrderRequest) Reset() {
	*x = RefundOrderRequest{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundOrderRequest) ProtoMessage() {}

func (x *RefundOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundOrderRequest.ProtoReflect.Descriptor instead.
func (*RefundOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{11}
}

func (x *RefundOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RefundOrderRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundOrderRequest) GetTaxBreakdownProvided() bool {
	if x != nil {
		return x.TaxBreakdownProvided
	}
	return false
}

func (x *RefundOrderRequest) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *RefundOrderRequest) GetDiscount() int64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *RefundOrderRequest) GetTax() int64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *RefundOrderRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RefundOrderRequest) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *RefundOrderRequest) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

type RefundOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Refund        *OrderRefund           `protobuf:"bytes,2,opt,name=refund,proto3" json:"refund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundOrderResponse) Reset() {
	*x = RefundOrderResponse{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundOrderResponse) ProtoMessage() {}

func (x *RefundOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundOrderResponse.ProtoReflect.Descriptor instead.
func (*RefundOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{12}
}

func (x *RefundOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *RefundOrderResponse) GetRefund() *OrderRefund {
	if x != nil {
		return x.Refund
	}
	return nil
}

// CreateOrderRequest records a purchase and starts paying for it. Called by
// a product backend with an Idempotency-Key; also idempotent on external_ref.
type CreateOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The product's own order id.
	ExternalRef string `protobuf:"bytes,1,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	InvoiceRef  string `protobuf:"bytes,2,opt,name=invoice_ref,json=invoiceRef,proto3" json:"invoice_ref,omitempty"`
	// Optional for a card-only guest purchase; required to pay from wallets.
	CustomerId string `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Currency   string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	// With tax_breakdown_provided, subtotal - discount + tax must equal total.
	// Without it, send only total: it is booked gross and flagged.
	TaxBreakdownProvided bool   `protobuf:"varint,5,opt,name=tax_breakdown_provided,json=taxBreakdownProvided,proto3" json:"tax_breakdown_provided,omitempty"`
	Subtotal             int64  `protobuf:"varint,6,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Discount             int64  `protobuf:"varint,7,opt,name=discount,proto3" json:"discount,omitempty"`
	Tax                  int64  `protobuf:"varint,8,opt,name=tax,proto3" json:"tax,omitempty"`
	Total                int64  `protobuf:"varint,9,opt,name=total,proto3" json:"total,omitempty"`
	TaxRate              string `protobuf:"bytes,10,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	// If given, they must sum to the subtotal.
	Lines []*OrderLine `protobuf:"bytes,11,rep,name=lines,proto3" json:"lines,omitempty"`
	// Explicit wallet shares. Or auto_tender: draw from the customer's wallets,
	// granted value first. A card pays whatever remains.
	WalletTenders []*WalletTender `protobuf:"bytes,12,rep,name=wallet_tenders,json=walletTenders,proto3" json:"wallet_tenders,omitempty"`
	AutoTender    bool            `protobuf:"varint,13,opt,name=auto_tender,json=autoTender,proto3" json:"auto_tender,omitempty"`
	Description   string          `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	ReturnUrl     string          `protobuf:"bytes,15,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{13}
}

func (x *CreateOrderRequest) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *CreateOrderRequest) GetInvoiceRef() string {
	if x != nil {
		return x.InvoiceRef
	}
	return ""
}

func (x *CreateOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrderRequest) GetTaxBreakdownProvided() bool {
	if x != nil {
		return x.TaxBreakdownProvided
	}
	return false
}

func (x *CreateOrderRequest) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *CreateOrderRequest) GetDiscount() int64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *CreateOrderRequest) GetTax() int64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *CreateOrderRequest) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CreateOrderRequest) GetTaxRate() string {
	if x != nil {
		return x.TaxRate
	}
	return ""
}

func (x *CreateOrderRequest) GetLines() []*OrderLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *CreateOrderRequest) GetWalletTenders() []*WalletTender {
	if x != nil {
		return x.WalletTenders
	}
	return nil
}

func (x *CreateOrderRequest) GetAutoTender() bool {
	if x != nil {
		return x.AutoTender
	}
	return false
}

func (x *CreateOrderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateOrderRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{14}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{15}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{16}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{17}
}

func (x *CancelOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{18}
}

func (x *CancelOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=v1.OrderStatus" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{19}
}

func (x *ListOrdersRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ListOrdersRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListOrdersRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListOrdersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Newest first. Summaries: lines, tenders and refunds come with GetOrder.
	Orders        []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_proto_openpay_v1_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_order_proto_rawDescGZIP(), []int{20}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_openpay_v1_order_proto protoreflect.FileDescriptor

const file_proto_openpay_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/openpay/v1/order.proto\x12\x02v1\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12'\n" +
	"\x0freference_price\x18\x04 \x01(\x03R\x0ereferencePrice\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1b\n" +
	"\ttax_class\x18\x06 \x01(\tR\btaxClass\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe5\x01\n" +
	"\x11CreateItemRequest\x120\n" +
	"\x04code\x18\x01 \x01(\tB\x1c\xfaB\x19r\x172\x15^[A-Za-z0-9_-]{1,50}$R\x04code\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x04name\x120\n" +
	"\x0freference_price\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\x0ereferencePrice\x12&\n" +
	"\bcurrency\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05R\x03INRR\bcurrency\x12$\n" +
	"\ttax_class\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x182R\btaxClass\"2\n" +
	"\x12CreateItemResponse\x12\x1c\n" +
	"\x04item\x18\x01 \x01(\v2\b.v1.ItemR\x04item\"\x12\n" +
	"\x10ListItemsRequest\"3\n" +
	"\x11ListItemsResponse\x12\x1e\n" +
	"\x05items\x18\x01 \x03(\v2\b.v1.ItemR\x05items\"\xb7\x01\n" +
	"\tOrderLine\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12*\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x18\xf4\x03R\vdescription\x12#\n" +
	"\bquantity\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\bquantity\x12(\n" +
	"\vunit_amount\x18\x04 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\n" +
	"unitAmount\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\"U\n" +
	"\fWalletTender\x12$\n" +
	"\twallet_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bwalletId\x12\x1f\n" +
	"\x06amount\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06amount\"n\n" +
	"\vOrderTender\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xc7\x06\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fexternal_ref\x18\x02 \x01(\tR\vexternalRef\x12\x1f\n" +
	"\vinvoice_ref\x18\x03 \x01(\tR\n" +
	"invoiceRef\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x12\x1f\n" +
	"\vcustomer_id\x18\x05 \x01(\tR\n" +
	"customerId\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bsubtotal\x18\a \x01(\x03R\bsubtotal\x12\x1a\n" +
	"\bdiscount\x18\b \x01(\x03R\bdiscount\x12\x10\n" +
	"\x03tax\x18\t \x01(\x03R\x03tax\x12\x14\n" +
	"\x05total\x18\n" +
	" \x01(\x03R\x05total\x12\x19\n" +
	"\btax_rate\x18\v \x01(\tR\ataxRate\x124\n" +
	"\x16tax_breakdown_provided\x18\f \x01(\bR\x14taxBreakdownProvided\x12'\n" +
	"\x06status\x18\r \x01(\x0e2\x0f.v1.OrderStatusR\x06status\x12%\n" +
	"\x0efailure_reason\x18\x0e \x01(\tR\rfailureReason\x12#\n" +
	"\x05lines\x18\x0f \x03(\v2\r.v1.OrderLineR\x05lines\x12)\n" +
	"\atenders\x18\x10 \x03(\v2\x0f.v1.OrderTenderR\atenders\x12%\n" +
	"\x0egateway_amount\x18\x11 \x01(\x03R\rgatewayAmount\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x12 \x01(\tR\tpaymentId\x12!\n" +
	"\fcheckout_url\x18\x13 \x01(\tR\vcheckoutUrl\x129\n" +
	"\n" +
	"expires_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x123\n" +
	"\apaid_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x129\n" +
	"\n" +
	"created_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12)\n" +
	"\arefunds\x18\x17 \x03(\v2\x0f.v1.OrderRefundR\arefunds\"\xf2\x02\n" +
	"\vOrderRefund\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bsubtotal\x18\x03 \x01(\x03R\bsubtotal\x12\x1a\n" +
	"\bdiscount\x18\x04 \x01(\x03R\bdiscount\x12\x10\n" +
	"\x03tax\x18\x05 \x01(\x03R\x03tax\x124\n" +
	"\x16tax_breakdown_provided\x18\x06 \x01(\bR\x14taxBreakdownProvided\x12 \n" +
	"\vdestination\x18\a \x01(\tR\vdestination\x12\x1f\n" +
	"\vreason_code\x18\b \x01(\tR\n" +
	"reasonCode\x12\x12\n" +
	"\x04memo\x18\t \x01(\tR\x04memo\x12)\n" +
	"\x05parts\x18\n" +
	" \x03(\v2\x13.v1.OrderRefundPartR\x05parts\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"c\n" +
	"\x0fOrderRefundPart\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x1b\n" +
	"\trefund_id\x18\x03 \x01(\tR\brefundId\"\xee\x02\n" +
	"\x12RefundOrderRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12\x1f\n" +
	"\x06amount\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06amount\x124\n" +
	"\x16tax_breakdown_provided\x18\x03 \x01(\bR\x14taxBreakdownProvided\x12#\n" +
	"\bsubtotal\x18\x04 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\bsubtotal\x12#\n" +
	"\bdiscount\x18\x05 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\bdiscount\x12\x19\n" +
	"\x03tax\x18\x06 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\x03tax\x129\n" +
	"\vdestination\x18\a \x01(\tB\x17\xfaB\x14r\x12R\x00R\x06sourceR\x06walletR\vdestination\x12*\n" +
	"\vreason_code\x18\b \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\n" +
	"reasonCode\x12\x1c\n" +
	"\x04memo\x18\t \x01(\tB\b\xfaB\x05r\x03\x18\xf4\x03R\x04memo\"_\n" +
	"\x13RefundOrderResponse\x12\x1f\n" +
	"\x05order\x18\x01 \x01(\v2\t.v1.OrderR\x05order\x12'\n" +
	"\x06refund\x18\x02 \x01(\v2\x0f.v1.OrderRefundR\x06refund\"\xe9\x04\n" +
	"\x12CreateOrderRequest\x12-\n" +
	"\fexternal_ref\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xc8\x01R\vexternalRef\x12)\n" +
	"\vinvoice_ref\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x18\xc8\x01R\n" +
	"invoiceRef\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12&\n" +
	"\bcurrency\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05R\x03INRR\bcurrency\x124\n" +
	"\x16tax_breakdown_provided\x18\x05 \x01(\bR\x14taxBreakdownProvided\x12#\n" +
	"\bsubtotal\x18\x06 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\bsubtotal\x12#\n" +
	"\bdiscount\x18\a \x01(\x03B\a\xfaB\x04\"\x02(\x00R\bdiscount\x12\x19\n" +
	"\x03tax\x18\b \x01(\x03B\a\xfaB\x04\"\x02(\x00R\x03tax\x12\x1d\n" +
	"\x05total\x18\t \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x05total\x12\"\n" +
	"\btax_rate\x18\n" +
	" \x01(\tB\a\xfaB\x04r\x02\x18\x14R\ataxRate\x12#\n" +
	"\x05lines\x18\v \x03(\v2\r.v1.OrderLineR\x05lines\x127\n" +
	"\x0ewallet_tenders\x18\f \x03(\v2\x10.v1.WalletTenderR\rwalletTenders\x12\x1f\n" +
	"\vauto_tender\x18\r \x01(\bR\n" +
	"autoTender\x12*\n" +
	"\vdescription\x18\x0e \x01(\tB\b\xfaB\x05r\x03\x18\xc8\x01R\vdescription\x12'\n" +
	"\n" +
	"return_url\x18\x0f \x01(\tB\b\xfaB\x05r\x03\x18\xd0\x0fR\treturnUrl\"6\n" +
	"\x13CreateOrderResponse\x12\x1f\n" +
	"\x05order\x18\x01 \x01(\v2\t.v1.OrderR\x05order\"*\n" +
	"\x0fGetOrderRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"3\n" +
	"\x10GetOrderResponse\x12\x1f\n" +
	"\x05order\x18\x01 \x01(\v2\t.v1.OrderR\x05order\"O\n" +
	"\x12CancelOrderRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12 \n" +
	"\x06reason\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x18\xf4\x03R\x06reason\"6\n" +
	"\x13CancelOrderResponse\x12\x1f\n" +
	"\x05order\x18\x01 \x01(\v2\t.v1.OrderR\x05order\"\xc8\x01\n" +
	"\x11ListOrdersRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0f.v1.OrderStatusB\b\xfaB\x05\x82\x01\x02\x10\x01R\x06status\x12\x1f\n" +
	"\x05limit\x18\x04 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\x05limit\x12\x1f\n" +
	"\x06offset\x18\x05 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x06offset\"M\n" +
	"\x12ListOrdersResponse\x12!\n" +
	"\x06orders\x18\x01 \x03(\v2\t.v1.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total*\xd9\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cORDER_STATUS_PENDING_PAYMENT\x10\x01\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x02\x12\x17\n" +
	"\x13ORDER_STATUS_FAILED\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x04\x12#\n" +
	"\x1fORDER_STATUS_PARTIALLY_REFUNDED\x10\x05\x12\x19\n" +
	"\x15ORDER_STATUS_REFUNDED\x10\x06B\x0eZ\f./openpay_v1b\x06proto3"

var (
	file_proto_openpay_v1_order_proto_rawDescOnce sync.Once
	file_proto_openpay_v1_order_proto_rawDescData []byte
)

func file_proto_openpay_v1_order_proto_rawDescGZIP() []byte {
	file_proto_openpay_v1_order_proto_rawDescOnce.Do(func() {
		file_proto_openpay_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_openpay_v1_order_proto_rawDesc), len(file_proto_openpay_v1_order_proto_rawDesc)))
	})
	return file_proto_openpay_v1_order_proto_rawDescData
}

var file_proto_openpay_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_openpay_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_openpay_v1_order_proto_goTypes = []any{
	(OrderStatus)(0),              // 0: v1.OrderStatus
	(*Item)(nil),                  // 1: v1.Item
	(*CreateItemRequest)(nil),     // 2: v1.CreateItemRequest
	(*CreateItemResponse)(nil),    // 3: v1.CreateItemResponse
	(*ListItemsRequest)(nil),      // 4: v1.ListItemsRequest
	(*ListItemsResponse)(nil),     // 5: v1.ListItemsResponse
	(*OrderLine)(nil),             // 6: v1.OrderLine
	(*WalletTender)(nil),          // 7: v1.WalletTender
	(*OrderTender)(nil),           // 8: v1.OrderTender
	(*Order)(nil),                 // 9: v1.Order
	(*OrderRefund)(nil),           // 10: v1.OrderRefund
	(*OrderRefundPart)(nil),       // 11: v1.OrderRefundPart
	(*RefundOrderRequest)(nil),    // 12: v1.RefundOrderRequest
	(*RefundOrderResponse)(nil),   // 13: v1.RefundOrderResponse
	(*CreateOrderRequest)(nil),    // 14: v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),   // 15: v1.CreateOrderResponse
	(*GetOrderRequest)(nil),       // 16: v1.GetOrderRequest
	(*GetOrderResponse)(nil),      // 17: v1.GetOrderResponse
	(*CancelOrderRequest)(nil),    // 18: v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),   // 19: v1.CancelOrderResponse
	(*ListOrdersRequest)(nil),     // 20: v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),    // 21: v1.ListOrdersResponse
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_proto_openpay_v1_order_proto_depIdxs = []int32{
	22, // 0: v1.Item.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: v1.CreateItemResponse.item:type_name -> v1.Item
	1,  // 2: v1.ListItemsResponse.items:type_name -> v1.Item
	0,  // 3: v1.Order.status:type_name -> v1.OrderStatus
	6,  // 4: v1.Order.lines:type_name -> v1.OrderLine
	8,  // 5: v1.Order.tenders:type_name -> v1.OrderTender
	22, // 6: v1.Order.expires_at:type_name -> google.protobuf.Timestamp
	22, // 7: v1.Order.paid_at:type_name -> google.protobuf.Timestamp
	22, // 8: v1.Order.created_at:type_name -> google.protobuf.Timestamp
	10, // 9: v1.Order.refunds:type_name -> v1.OrderRefund
	11, // 10: v1.OrderRefund.parts:type_name -> v1.OrderRefundPart
	22, // 11: v1.OrderRefund.created_at:type_name -> google.protobuf.Timestamp
	9,  // 12: v1.RefundOrderResponse.order:type_name -> v1.Order
	10, // 13: v1.RefundOrderResponse.refund:type_name -> v1.OrderRefund
	6,  // 14: v1.CreateOrderRequest.lines:type_name -> v1.OrderLine
	7,  // 15: v1.CreateOrderRequest.wallet_tenders:type_name -> v1.WalletTender
	9,  // 16: v1.CreateOrderResponse.order:type_name -> v1.Order
	9,  // 17: v1.GetOrderResponse.order:type_name -> v1.Order
	9,  // 18: v1.CancelOrderResponse.order:type_name -> v1.Order
	0,  // 19: v1.ListOrdersRequest.status:type_name -> v1.OrderStatus
	9,  // 20: v1.ListOrdersResponse.orders:type_name -> v1.Order
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_openpay_v1_order_proto_init() }
func file_proto_openpay_v1_order_proto_init() {
	if File_proto_openpay_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_openpay_v1_order_proto_rawDesc), len(file_proto_openpay_v1_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_openpay_v1_order_proto_goTypes,
		DependencyIndexes: file_proto_openpay_v1_order_proto_depIdxs,
		EnumInfos:         file_proto_openpay_v1_order_proto_enumTypes,
		MessageInfos:      file_proto_openpay_v1_order_proto_msgTypes,
	}.Build()
	File_proto_openpay_v1_order_proto = out.File
	file_proto_openpay_v1_order_proto_goTypes = nil
	file_proto_openpay_v1_order_proto_depIdxs = nil
}
