// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/openpay/v1/payment.proto

package openpay_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PaymentAttempt with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PaymentAttempt) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentAttempt with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaymentAttemptMultiError,
// or nil if none found.
func (m *PaymentAttempt) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentAttempt) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Provider

	// no validation rules for RoutingReason

	// no validation rules for ProviderPaymentId

	// no validation rules for Status

	// no validation rules for FailureCode

	// no validation rules for FailureReason

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PaymentAttemptValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PaymentAttemptValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PaymentAttemptValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PaymentAttemptMultiError(errors)
	}

	return nil
}

// PaymentAttemptMultiError is an error wrapping multiple validation errors
// returned by PaymentAttempt.ValidateAll() if the designated constraints
// aren't met.
type PaymentAttemptMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentAttemptMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentAttemptMultiError) AllErrors() []error { return m }

// PaymentAttemptValidationError is the validation error returned by
// PaymentAttempt.Validate if the designated constraints aren't met.
type PaymentAttemptValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentAttemptValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentAttemptValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentAttemptValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentAttemptValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentAttemptValidationError) ErrorName() string { return "PaymentAttemptValidationError" }

// Error satisfies the builtin error interface
func (e PaymentAttemptValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentAttempt.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentAttemptValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentAttemptValidationError{}

// Validate checks the field values on PaymentTransition with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PaymentTransition) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaymentTransition with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PaymentTransitionMultiError, or nil if none found.
func (m *PaymentTransition) ValidateAll() error {
	return m.validate(true)
}

func (m *PaymentTransition) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for From

	// no validation rules for To

	// no validation rules for Source

	// no validation rules for Reference

	// no validation rules for Detail

	if all {
		switch v := interface{}(m.GetAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PaymentTransitionValidationError{
					field:  "At",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PaymentTransitionValidationError{
					field:  "At",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PaymentTransitionValidationError{
				field:  "At",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PaymentTransitionMultiError(errors)
	}

	return nil
}

// PaymentTransitionMultiError is an error wrapping multiple validation errors
// returned by PaymentTransition.ValidateAll() if the designated constraints
// aren't met.
type PaymentTransitionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentTransitionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentTransitionMultiError) AllErrors() []error { return m }

// PaymentTransitionValidationError is the validation error returned by
// PaymentTransition.Validate if the designated constraints aren't met.
type PaymentTransitionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentTransitionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentTransitionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentTransitionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentTransitionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentTransitionValidationError) ErrorName() string {
	return "PaymentTransitionValidationError"
}

// Error satisfies the builtin error interface
func (e PaymentTransitionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentTransition.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentTransitionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentTransitionValidationError{}

// Validate checks the field values on Payment with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Payment) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Payment with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PaymentMultiError, or nil if none found.
func (m *Payment) ValidateAll() error {
	return m.validate(true)
}

func (m *Payment) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ProductId

	// no validation rules for CustomerId

	// no validation rules for Purpose

	// no validation rules for WalletId

	// no validation rules for Amount

	// no validation rules for Currency

	// no validation rules for Status

	// no validation rules for Application

	// no validation rules for Provider

	// no validation rules for CapturedAmount

	// no validation rules for CheckoutUrl

	// no validation rules for FailureCode

	// no validation rules for FailureReason

	// no validation rules for Description

	if all {
		switch v := interface{}(m.GetExpiresAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PaymentValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PaymentValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpiresAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PaymentValidationError{
				field:  "ExpiresAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PaymentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PaymentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PaymentValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PaymentValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PaymentValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PaymentValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetAttempts() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PaymentValidationError{
						field:  fmt.Sprintf("Attempts[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PaymentValidationError{
						field:  fmt.Sprintf("Attempts[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PaymentValidationError{
					field:  fmt.Sprintf("Attempts[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetTransitions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PaymentValidationError{
						field:  fmt.Sprintf("Transitions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PaymentValidationError{
						field:  fmt.Sprintf("Transitions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PaymentValidationError{
					field:  fmt.Sprintf("Transitions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for RefundedAmount

	if len(errors) > 0 {
		return PaymentMultiError(errors)
	}

	return nil
}

// PaymentMultiError is an error wrapping multiple validation errors returned
// by Payment.ValidateAll() if the designated constraints aren't met.
type PaymentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaymentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaymentMultiError) AllErrors() []error { return m }

// PaymentValidationError is the validation error returned by Payment.Validate
// if the designated constraints aren't met.
type PaymentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentValidationError) ErrorName() string { return "PaymentValidationError" }

// Error satisfies the builtin error interface
func (e PaymentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPayment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentValidationError{}

// Validate checks the field values on Refund with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Refund) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Refund with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RefundMultiError, or nil if none found.
func (m *Refund) ValidateAll() error {
	return m.validate(true)
}

func (m *Refund) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for PaymentId

	// no validation rules for Amount

	// no validation rules for Currency

	// no validation rules for Status

	// no validation rules for Source

	// no validation rules for ReasonCode

	// no validation rules for Memo

	// no validation rules for ProviderRefundId

	// no validation rules for FailureReason

	// no validation rules for RequestedBy

	if all {
		switch v := interface{}(m.GetProcessedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RefundValidationError{
					field:  "ProcessedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RefundValidationError{
					field:  "ProcessedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProcessedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RefundValidationError{
				field:  "ProcessedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RefundValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RefundValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RefundValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RefundMultiError(errors)
	}

	return nil
}

// RefundMultiError is an error wrapping multiple validation errors returned by
// Refund.ValidateAll() if the designated constraints aren't met.
type RefundMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefundMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefundMultiError) AllErrors() []error { return m }

// RefundValidationError is the validation error returned by Refund.Validate if
// the designated constraints aren't met.
type RefundValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefundValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefundValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefundValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefundValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefundValidationError) ErrorName() string { return "RefundValidationError" }

// Error satisfies the builtin error interface
func (e RefundValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefund.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefundValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefundValidationError{}

// Validate checks the field values on CreateRefundRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRefundRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRefundRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRefundRequestMultiError, or nil if none found.
func (m *CreateRefundRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRefundRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetPaymentId()) < 1 {
		err := CreateRefundRequestValidationError{
			field:  "PaymentId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAmount() <= 0 {
		err := CreateRefundRequestValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetReasonCode()); l < 1 || l > 50 {
		err := CreateRefundRequestValidationError{
			field:  "ReasonCode",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetMemo()); l < 1 || l > 500 {
		err := CreateRefundRequestValidationError{
			field:  "Memo",
			reason: "value length must be between 1 and 500 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateRefundRequestMultiError(errors)
	}

	return nil
}

// CreateRefundRequestMultiError is an error wrapping multiple validation
// errors returned by CreateRefundRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateRefundRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRefundRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRefundRequestMultiError) AllErrors() []error { return m }

// CreateRefundRequestValidationError is the validation error returned by
// CreateRefundRequest.Validate if the designated constraints aren't met.
type CreateRefundRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRefundRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRefundRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRefundRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRefundRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRefundRequestValidationError) ErrorName() string {
	return "CreateRefundRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRefundRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRefundRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRefundRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRefundRequestValidationError{}

// Validate checks the field values on CreateRefundResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRefundResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRefundResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRefundResponseMultiError, or nil if none found.
func (m *CreateRefundResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRefundResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRefund()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateRefundResponseValidationError{
					field:  "Refund",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateRefundResponseValidationError{
					field:  "Refund",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRefund()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateRefundResponseValidationError{
				field:  "Refund",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateRefundResponseMultiError(errors)
	}

	return nil
}

// CreateRefundResponseMultiError is an error wrapping multiple validation
// errors returned by CreateRefundResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateRefundResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRefundResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRefundResponseMultiError) AllErrors() []error { return m }

// CreateRefundResponseValidationError is the validation error returned by
// CreateRefundResponse.Validate if the designated constraints aren't met.
type CreateRefundResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRefundResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRefundResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRefundResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRefundResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRefundResponseValidationError) ErrorName() string {
	return "CreateRefundResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRefundResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRefundResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRefundResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRefundResponseValidationError{}

// Validate checks the field values on GetRefundRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetRefundRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRefundRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRefundRequestMultiError, or nil if none found.
func (m *GetRefundRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRefundRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := GetRefundRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetRefundRequestMultiError(errors)
	}

	return nil
}

// GetRefundRequestMultiError is an error wrapping multiple validation errors
// returned by GetRefundRequest.ValidateAll() if the designated constraints
// aren't met.
type GetRefundRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRefundRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRefundRequestMultiError) AllErrors() []error { return m }

// GetRefundRequestValidationError is the validation error returned by
// GetRefundRequest.Validate if the designated constraints aren't met.
type GetRefundRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRefundRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRefundRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRefundRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRefundRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRefundRequestValidationError) ErrorName() string { return "GetRefundRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetRefundRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRefundRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRefundRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRefundRequestValidationError{}

// Validate checks the field values on GetRefundResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetRefundResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRefundResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRefundResponseMultiError, or nil if none found.
func (m *GetRefundResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRefundResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRefund()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetRefundResponseValidationError{
					field:  "Refund",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetRefundResponseValidationError{
					field:  "Refund",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRefund()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetRefundResponseValidationError{
				field:  "Refund",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetRefundResponseMultiError(errors)
	}

	return nil
}

// GetRefundResponseMultiError is an error wrapping multiple validation errors
// returned by GetRefundResponse.ValidateAll() if the designated constraints
// aren't met.
type GetRefundResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRefundResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRefundResponseMultiError) AllErrors() []error { return m }

// GetRefundResponseValidationError is the validation error returned by
// GetRefundResponse.Validate if the designated constraints aren't met.
type GetRefundResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRefundResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRefundResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRefundResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRefundResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRefundResponseValidationError) ErrorName() string {
	return "GetRefundResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRefundResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRefundResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRefundResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRefundResponseValidationError{}

// Validate checks the field values on ListRefundsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRefundsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRefundsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRefundsRequestMultiError, or nil if none found.
func (m *ListRefundsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRefundsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetPaymentId()) < 1 {
		err := ListRefundsRequestValidationError{
			field:  "PaymentId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListRefundsRequestMultiError(errors)
	}

	return nil
}

// ListRefundsRequestMultiError is an error wrapping multiple validation errors
// returned by ListRefundsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListRefundsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRefundsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRefundsRequestMultiError) AllErrors() []error { return m }

// ListRefundsRequestValidationError is the validation error returned by
// ListRefundsRequest.Validate if the designated constraints aren't met.
type ListRefundsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRefundsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRefundsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRefundsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRefundsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRefundsRequestValidationError) ErrorName() string {
	return "ListRefundsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRefundsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRefundsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRefundsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRefundsRequestValidationError{}

// Validate checks the field values on ListRefundsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRefundsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRefundsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRefundsResponseMultiError, or nil if none found.
func (m *ListRefundsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRefundsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRefunds() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRefundsResponseValidationError{
						field:  fmt.Sprintf("Refunds[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRefundsResponseValidationError{
						field:  fmt.Sprintf("Refunds[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRefundsResponseValidationError{
					field:  fmt.Sprintf("Refunds[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListRefundsResponseMultiError(errors)
	}

	return nil
}

// ListRefundsResponseMultiError is an error wrapping multiple validation
// errors returned by ListRefundsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListRefundsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRefundsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRefundsResponseMultiError) AllErrors() []error { return m }

// ListRefundsResponseValidationError is the validation error returned by
// ListRefundsResponse.Validate if the designated constraints aren't met.
type ListRefundsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRefundsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRefundsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRefundsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRefundsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRefundsResponseValidationError) ErrorName() string {
	return "ListRefundsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRefundsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRefundsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRefundsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRefundsResponseValidationError{}

// Validate checks the field values on CreatePaymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreatePaymentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreatePaymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreatePaymentRequestMultiError, or nil if none found.
func (m *CreatePaymentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreatePaymentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _CreatePaymentRequest_Purpose_NotInLookup[m.GetPurpose()]; ok {
		err := CreatePaymentRequestValidationError{
			field:  "Purpose",
			reason: "value must not be in list [PAYMENT_PURPOSE_UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := PaymentPurpose_name[int32(m.GetPurpose())]; !ok {
		err := CreatePaymentRequestValidationError{
			field:  "Purpose",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetWalletId()) < 1 {
		err := CreatePaymentRequestValidationError{
			field:  "WalletId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAmount() <= 0 {
		err := CreatePaymentRequestValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _CreatePaymentRequest_Currency_InLookup[m.GetCurrency()]; !ok {
		err := CreatePaymentRequestValidationError{
			field:  "Currency",
			reason: "value must be in list [INR]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) > 200 {
		err := CreatePaymentRequestValidationError{
			field:  "Description",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetReturnUrl()) > 2000 {
		err := CreatePaymentRequestValidationError{
			field:  "ReturnUrl",
			reason: "value length must be at most 2000 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreatePaymentRequestMultiError(errors)
	}

	return nil
}

// CreatePaymentRequestMultiError is an error wrapping multiple validation
// errors returned by CreatePaymentRequest.ValidateAll() if the designated
// constraints aren't met.
type CreatePaymentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatePaymentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatePaymentRequestMultiError) AllErrors() []error { return m }

// CreatePaymentRequestValidationError is the validation error returned by
// CreatePaymentRequest.Validate if the designated constraints aren't met.
type CreatePaymentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePaymentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePaymentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePaymentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePaymentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePaymentRequestValidationError) ErrorName() string {
	return "CreatePaymentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePaymentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePaymentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePaymentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePaymentRequestValidationError{}

var _CreatePaymentRequest_Purpose_NotInLookup = map[PaymentPurpose]struct{}{
	0: {},
}

var _CreatePaymentRequest_Currency_InLookup = map[string]struct{}{
	"INR": {},
}

// Validate checks the field values on CreatePaymentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreatePaymentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreatePaymentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreatePaymentResponseMultiError, or nil if none found.
func (m *CreatePaymentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreatePaymentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPayment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreatePaymentResponseValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreatePaymentResponseValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPayment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreatePaymentResponseValidationError{
				field:  "Payment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreatePaymentResponseMultiError(errors)
	}

	return nil
}

// CreatePaymentResponseMultiError is an error wrapping multiple validation
// errors returned by CreatePaymentResponse.ValidateAll() if the designated
// constraints aren't met.
type CreatePaymentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatePaymentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatePaymentResponseMultiError) AllErrors() []error { return m }

// CreatePaymentResponseValidationError is the validation error returned by
// CreatePaymentResponse.Validate if the designated constraints aren't met.
type CreatePaymentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePaymentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePaymentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePaymentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePaymentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePaymentResponseValidationError) ErrorName() string {
	return "CreatePaymentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePaymentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePaymentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePaymentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePaymentResponseValidationError{}

// Validate checks the field values on GetPaymentRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetPaymentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPaymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPaymentRequestMultiError, or nil if none found.
func (m *GetPaymentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPaymentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := GetPaymentRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetPaymentRequestMultiError(errors)
	}

	return nil
}

// GetPaymentRequestMultiError is an error wrapping multiple validation errors
// returned by GetPaymentRequest.ValidateAll() if the designated constraints
// aren't met.
type GetPaymentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPaymentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPaymentRequestMultiError) AllErrors() []error { return m }

// GetPaymentRequestValidationError is the validation error returned by
// GetPaymentRequest.Validate if the designated constraints aren't met.
type GetPaymentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPaymentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPaymentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPaymentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPaymentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPaymentRequestValidationError) ErrorName() string {
	return "GetPaymentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetPaymentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPaymentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPaymentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPaymentRequestValidationError{}

// Validate checks the field values on GetPaymentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPaymentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPaymentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPaymentResponseMultiError, or nil if none found.
func (m *GetPaymentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPaymentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPayment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetPaymentResponseValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetPaymentResponseValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPayment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetPaymentResponseValidationError{
				field:  "Payment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetPaymentResponseMultiError(errors)
	}

	return nil
}

// GetPaymentResponseMultiError is an error wrapping multiple validation errors
// returned by GetPaymentResponse.ValidateAll() if the designated constraints
// aren't met.
type GetPaymentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPaymentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPaymentResponseMultiError) AllErrors() []error { return m }

// GetPaymentResponseValidationError is the validation error returned by
// GetPaymentResponse.Validate if the designated constraints aren't met.
type GetPaymentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPaymentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPaymentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPaymentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPaymentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPaymentResponseValidationError) ErrorName() string {
	return "GetPaymentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetPaymentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPaymentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPaymentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPaymentResponseValidationError{}

// Validate checks the field values on ListPaymentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPaymentsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPaymentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPaymentsRequestMultiError, or nil if none found.
func (m *ListPaymentsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPaymentsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetLimit(); val < 0 || val > 100 {
		err := ListPaymentsRequestValidationError{
			field:  "Limit",
			reason: "value must be inside range [0, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetOffset() < 0 {
		err := ListPaymentsRequestValidationError{
			field:  "Offset",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ProductId

	// no validation rules for CustomerId

	if _, ok := PaymentStatus_name[int32(m.GetStatus())]; !ok {
		err := ListPaymentsRequestValidationError{
			field:  "Status",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ListPaymentsRequestMultiError(errors)
	}

	return nil
}

// ListPaymentsRequestMultiError is an error wrapping multiple validation
// errors returned by ListPaymentsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListPaymentsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPaymentsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPaymentsRequestMultiError) AllErrors() []error { return m }

// ListPaymentsRequestValidationError is the validation error returned by
// ListPaymentsRequest.Validate if the designated constraints aren't met.
type ListPaymentsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPaymentsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPaymentsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPaymentsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPaymentsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPaymentsRequestValidationError) ErrorName() string {
	return "ListPaymentsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListPaymentsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPaymentsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPaymentsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPaymentsRequestValidationError{}

// Validate checks the field values on ListPaymentsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPaymentsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPaymentsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPaymentsResponseMultiError, or nil if none found.
func (m *ListPaymentsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPaymentsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPayments() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListPaymentsResponseValidationError{
						field:  fmt.Sprintf("Payments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListPaymentsResponseValidationError{
						field:  fmt.Sprintf("Payments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPaymentsResponseValidationError{
					field:  fmt.Sprintf("Payments[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListPaymentsResponseMultiError(errors)
	}

	return nil
}

// ListPaymentsResponseMultiError is an error wrapping multiple validation
// errors returned by ListPaymentsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListPaymentsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPaymentsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPaymentsResponseMultiError) AllErrors() []error { return m }

// ListPaymentsResponseValidationError is the validation error returned by
// ListPaymentsResponse.Validate if the designated constraints aren't met.
type ListPaymentsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPaymentsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPaymentsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPaymentsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPaymentsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPaymentsResponseValidationError) ErrorName() string {
	return "ListPaymentsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPaymentsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPaymentsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPaymentsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPaymentsResponseValidationError{}

// Validate checks the field values on SyncPaymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SyncPaymentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SyncPaymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SyncPaymentRequestMultiError, or nil if none found.
func (m *SyncPaymentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SyncPaymentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := SyncPaymentRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SyncPaymentRequestMultiError(errors)
	}

	return nil
}

// SyncPaymentRequestMultiError is an error wrapping multiple validation errors
// returned by SyncPaymentRequest.ValidateAll() if the designated constraints
// aren't met.
type SyncPaymentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SyncPaymentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SyncPaymentRequestMultiError) AllErrors() []error { return m }

// SyncPaymentRequestValidationError is the validation error returned by
// SyncPaymentRequest.Validate if the designated constraints aren't met.
type SyncPaymentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SyncPaymentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SyncPaymentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SyncPaymentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SyncPaymentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SyncPaymentRequestValidationError) ErrorName() string {
	return "SyncPaymentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SyncPaymentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSyncPaymentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SyncPaymentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SyncPaymentRequestValidationError{}

// Validate checks the field values on SyncPaymentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SyncPaymentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SyncPaymentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SyncPaymentResponseMultiError, or nil if none found.
func (m *SyncPaymentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SyncPaymentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPayment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SyncPaymentResponseValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SyncPaymentResponseValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPayment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SyncPaymentResponseValidationError{
				field:  "Payment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SyncPaymentResponseMultiError(errors)
	}

	return nil
}

// SyncPaymentResponseMultiError is an error wrapping multiple validation
// errors returned by SyncPaymentResponse.ValidateAll() if the designated
// constraints aren't met.
type SyncPaymentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SyncPaymentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SyncPaymentResponseMultiError) AllErrors() []error { return m }

// SyncPaymentResponseValidationError is the validation error returned by
// SyncPaymentResponse.Validate if the designated constraints aren't met.
type SyncPaymentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SyncPaymentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SyncPaymentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SyncPaymentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SyncPaymentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SyncPaymentResponseValidationError) ErrorName() string {
	return "SyncPaymentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SyncPaymentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSyncPaymentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SyncPaymentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SyncPaymentResponseValidationError{}
