// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/openpay/v1/provider.proto

package openpay_v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderOverride int32

const (
	ProviderOverride_PROVIDER_OVERRIDE_UNSPECIFIED ProviderOverride = 0
	// Back to normal routing by priority and health.
	ProviderOverride_PROVIDER_OVERRIDE_NONE ProviderOverride = 1
	// Take out of rotation: no new attempts.
	ProviderOverride_PROVIDER_OVERRIDE_DISABLED ProviderOverride = 2
	// Send every new attempt here, whatever its priority or health.
	ProviderOverride_PROVIDER_OVERRIDE_FORCED ProviderOverride = 3
)

// Enum value maps for ProviderOverride.
var (
	ProviderOverride_name = map[int32]string{
		0: "PROVIDER_OVERRIDE_UNSPECIFIED",
		1: "PROVIDER_OVERRIDE_NONE",
		2: "PROVIDER_OVERRIDE_DISABLED",
		3: "PROVIDER_OVERRIDE_FORCED",
	}
	ProviderOverride_value = map[string]int32{
		"PROVIDER_OVERRIDE_UNSPECIFIED": 0,
		"PROVIDER_OVERRIDE_NONE":        1,
		"PROVIDER_OVERRIDE_DISABLED":    2,
		"PROVIDER_OVERRIDE_FORCED":      3,
	}
)

func (x ProviderOverride) Enum() *ProviderOverride {
	p := new(ProviderOverride)
	*p = x
	return p
}

func (x ProviderOverride) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderOverride) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_openpay_v1_provider_proto_enumTypes[0].Descriptor()
}

func (ProviderOverride) Type() protoreflect.EnumType {
	return &file_proto_openpay_v1_provider_proto_enumTypes[0]
}

func (x ProviderOverride) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderOverride.Descriptor instead.
func (ProviderOverride) EnumDescriptor() ([]byte, []int) {
	return file_proto_openpay_v1_provider_proto_rawDescGZIP(), []int{0}
}

type ProviderStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Position in the configured priority list, 1 first.
	Priority int32 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	// False while the circuit is open after repeated outage failures.
	Healthy             bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ConsecutiveFailures int32                  `protobuf:"varint,4,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	CircuitOpenUntil    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=circuit_open_until,json=circuitOpenUntil,proto3" json:"circuit_open_until,omitempty"`
	LastError           string                 `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// Operator override: no new attempts, or every new attempt.
	Disabled       bool   `protobuf:"varint,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Forced         bool   `protobuf:"varint,8,opt,name=forced,proto3" json:"forced,omitempty"`
	OverrideReason string `protobuf:"bytes,9,opt,name=override_reason,json=overrideReason,proto3" json:"override_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderStatus) Reset() {
	*x = ProviderStatus{}
	mi := &file_proto_openpay_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatus) ProtoMessage() {}

func (x *ProviderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatus.ProtoReflect.Descriptor instead.
func (*ProviderStatus) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderStatus) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ProviderStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ProviderStatus) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *ProviderStatus) GetCircuitOpenUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.CircuitOpenUntil
	}
	return nil
}

func (x *ProviderStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ProviderStatus) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *ProviderStatus) GetForced() bool {
	if x != nil {
		return x.Forced
	}
	return false
}

func (x *ProviderStatus) GetOverrideReason() string {
	if x != nil {
		return x.OverrideReason
	}
	return ""
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_proto_openpay_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_provider_proto_rawDescGZIP(), []int{1}
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderStatus      `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_proto_openpay_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ListProvidersResponse) GetProviders() []*ProviderStatus {
	if x != nil {
		return x.Providers
	}
	return nil
}

// SetProviderOverrideRequest is the kill-switch: takes effect in every
// process on the next routing decision, without a deploy. In-flight payments
// stay where they are — failover never happens mid-payment.
type SetProviderOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Override      ProviderOverride       `protobuf:"varint,2,opt,name=override,proto3,enum=v1.ProviderOverride" json:"override,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProviderOverrideRequest) Reset() {
	*x = SetProviderOverrideRequest{}
	mi := &file_proto_openpay_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProviderOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProviderOverrideRequest) ProtoMessage() {}

func (x *SetProviderOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProviderOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetProviderOverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *SetProviderOverrideRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetProviderOverrideRequest) GetOverride() ProviderOverride {
	if x != nil {
		return x.Override
	}
	return ProviderOverride_PROVIDER_OVERRIDE_UNSPECIFIED
}

func (x *SetProviderOverrideRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SetProviderOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderStatus        `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProviderOverrideResponse) Reset() {
	*x = SetProviderOverrideResponse{}
	mi := &file_proto_openpay_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProviderOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProviderOverrideResponse) ProtoMessage() {}

func (x *SetProviderOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openpay_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProviderOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetProviderOverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_openpay_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *SetProviderOverrideResponse) GetProvider() *ProviderStatus {
	if x != nil {
		return x.Provider
	}
	return nil
}

var File_proto_openpay_v1_provider_proto protoreflect.FileDescriptor

const file_proto_openpay_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/openpay/v1/provider.proto\x12\x02v1\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x02\n" +
	"\x0eProviderStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x121\n" +
	"\x14consecutive_failures\x18\x04 \x01(\x05R\x13consecutiveFailures\x12H\n" +
	"\x12circuit_open_until\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x10circuitOpenUntil\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\x12\x1a\n" +
	"\bdisabled\x18\a \x01(\bR\bdisabled\x12\x16\n" +
	"\x06forced\x18\b \x01(\bR\x06forced\x12'\n" +
	"\x0foverride_reason\x18\t \x01(\tR\x0eoverrideReason\"\x16\n" +
	"\x14ListProvidersRequest\"I\n" +
	"\x15ListProvidersResponse\x120\n" +
	"\tproviders\x18\x01 \x03(\v2\x12.v1.ProviderStatusR\tproviders\"\x9b\x01\n" +
	"\x1aSetProviderOverrideRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12<\n" +
	"\boverride\x18\x02 \x01(\x0e2\x14.v1.ProviderOverrideB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\boverride\x12\"\n" +
	"\x06reason\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xf4\x03R\x06reason\"M\n" +
	"\x1bSetProviderOverrideResponse\x12.\n" +
	"\bprovider\x18\x01 \x01(\v2\x12.v1.ProviderStatusR\bprovider*\x8f\x01\n" +
	"\x10ProviderOverride\x12!\n" +
	"\x1dPROVIDER_OVERRIDE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROVIDER_OVERRIDE_NONE\x10\x01\x12\x1e\n" +
	"\x1aPROVIDER_OVERRIDE_DISABLED\x10\x02\x12\x1c\n" +
	"\x18PROVIDER_OVERRIDE_FORCED\x10\x03B\x0eZ\f./openpay_v1b\x06proto3"

var (
	file_proto_openpay_v1_provider_proto_rawDescOnce sync.Once
	file_proto_openpay_v1_provider_proto_rawDescData []byte
)

func file_proto_openpay_v1_provider_proto_rawDescGZIP() []byte {
	file_proto_openpay_v1_provider_proto_rawDescOnce.Do(func() {
		file_proto_openpay_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_openpay_v1_provider_proto_rawDesc), len(file_proto_openpay_v1_provider_proto_rawDesc)))
	})
	return file_proto_openpay_v1_provider_proto_rawDescData
}

var file_proto_openpay_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_openpay_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_openpay_v1_provider_proto_goTypes = []any{
	(ProviderOverride)(0),               // 0: v1.ProviderOverride
	(*ProviderStatus)(nil),              // 1: v1.ProviderStatus
	(*ListProvidersRequest)(nil),        // 2: v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),       // 3: v1.ListProvidersResponse
	(*SetProviderOverrideRequest)(nil),  // 4: v1.SetProviderOverrideRequest
	(*SetProviderOverrideResponse)(nil), // 5: v1.SetProviderOverrideResponse
	(*timestamppb.Timestamp)(nil),       // 6: google.protobuf.Timestamp
}
var file_proto_openpay_v1_provider_proto_depIdxs = []int32{
	6, // 0: v1.ProviderStatus.circuit_open_until:type_name -> google.protobuf.Timestamp
	1, // 1: v1.ListProvidersResponse.providers:type_name -> v1.ProviderStatus
	0, // 2: v1.SetProviderOverrideRequest.override:type_name -> v1.ProviderOverride
	1, // 3: v1.SetProviderOverrideResponse.provider:type_name -> v1.ProviderStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_openpay_v1_provider_proto_init() }
func file_proto_openpay_v1_provider_proto_init() {
	if File_proto_openpay_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_openpay_v1_provider_proto_rawDesc), len(file_proto_openpay_v1_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_openpay_v1_provider_proto_goTypes,
		DependencyIndexes: file_proto_openpay_v1_provider_proto_depIdxs,
		EnumInfos:         file_proto_openpay_v1_provider_proto_enumTypes,
		MessageInfos:      file_proto_openpay_v1_provider_proto_msgTypes,
	}.Build()
	File_proto_openpay_v1_provider_proto = out.File
	file_proto_openpay_v1_provider_proto_goTypes = nil
	file_proto_openpay_v1_provider_proto_depIdxs = nil
}
